### ISSUE TITLE
Request: kindly add release build for windows also.

### ISSUE THREAD

**Issue by leefordjudes** [ubuntu-flutter-community/musicpod#1006]

**Comment by Crocodile73** [comment]
Has Windows builds been scrapped?

**Comment by Feichtmeier** [comment]
Hey guys, no they haven't. Sorry for the inconvenience..
Currently sick can't work on windows builds and they stopped working for me last month for no reason. I want to try to create this new package format for the windows store instead.
Linux and MacOS packages are built automatically and everything is fine, however Windows exe creation is a weirdly manual workflow that keeps breaking very often. Most of the time I managed to fix it but last time I didn't do I want to switch over to this msix format for the store.
I'll keep you updated when I'm back, it's very high on my prio. Sorry again

**Comment by leefordjudes** [comment]
Thank you so much, 
I am waiting for the Windows build.

**Comment by Feichtmeier** [comment]
@leefordjudes @Crocodile73 hey guys I think i fixed it please try

https://github.com/ubuntu-flutter-community/musicpod/releases/tag/v2.4.0

**Comment by Crocodile73** [comment]
Sorry for the late reply. All good with windows build for me
