### ISSUE TITLE
feat(ExposeService): ListenBrainz integration

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/musicpod#1029]
And don't forget ListenBrainz, another popular (?) alternative to last.fm

_Originally posted by @Derkades in https://github.com/ubuntu-flutter-community/musicpod/issues/874#issuecomment-2299685775_
            

https://pub.dev/packages/listenbrainz_dart

**Comment by CosmicRaptor** [comment]
I'll try to implement this tomorrow! It'll use the same expose service that I added for last.fm so it will have the same issues that our current last.fm build has(ie it scrobbles immediately and not after 30s or half the song played)

**Comment by Feichtmeier** [comment]
dont know if you checked my code changes after your nice contribution, but I wrapped last fm in a service, would be better if you do this for listenbrainz as well, I need to do this for discord too

**Comment by CosmicRaptor** [comment]
> dont know if you checked my code changes after your nice contribution, but I wrapped last fm in a service, would be better if you do this for listenbrainz as well, I need to do this for discord too

I see. I'll follow the same implementation paradigm!
