### ISSUE TITLE
Use the cover image stored inside the album folders

### ISSUE THREAD

**Issue by ClementBeal** [ubuntu-flutter-community/musicpod#1048]
Hi!

There is a lot of albums in my library that are shown without the cover image, probably because they are not stored inside the track metadata.

Very often, we can find the cover image inside the album folder. It has a name like `front`, `cover`, `album` etc...

**Comment by Feichtmeier** [comment]
Okay 👍 I think that's doable 
Especially now since I totally moved the step where the cover is loaded out of the step where the song metadata is loaded

**Comment by Feichtmeier** [comment]
@ClementBeal check the snap from edge on ubuntu in about 30 mins and if it doesnt work just re-open this issue here

**Comment by nghiatm-twendee** [comment]
Never mind, it just appears. I don't know why though. I close the app and after a while, open it and it just shows

<img width="1918" height="1035" alt="Image" src="https://github.com/user-attachments/assets/9bdc2626-ee61-4ed8-834d-5136d74b6b99" />
