### ISSUE TITLE
Make local music genre menu case insensitive

### ISSUE THREAD

**Issue by Froozigiusz** [ubuntu-flutter-community/musicpod#1081]
This topic is one of the greatest unknowns when it comes to proper metadata organization of your collection, as the answer to it lies in the realm of philosophy. Because of that, there are currently about three standards of embedding music genre information into a file.

Because pretty much all of those issues come from case sensitivity rules, I suggest making the local music genre menu case **in**sensitive. This way you won't get your collection cut into smaller chunks because of arbitrary rules.
![image](https://github.com/user-attachments/assets/67c890ca-be36-4b25-aa19-1989be4ac8d4)

I know that this won't fix the underlying problem of lack of consistency, however I strive for ✨the pretty✨™ with this issue. Maybe a small option in the settings menu could choose what type of capitalsation you persnally want/prefer to see:
- First letter capitalised only,
- Every Word Capitalised,
- no capitalisation.

**Comment by Feichtmeier** [comment]
@Froozigiusz hi! Yes the way it is displayed can ofc be disconnected from the way it is read! Will fix

**Comment by Feichtmeier** [comment]
@Froozigiusz I see you use ubuntu i assume you use musicpod from the snap
in 20 mins the snap in edge has the potential fix please have a look if this fixes it for you

**Comment by Froozigiusz** [comment]
@Feichtmeier ~~I think the update did come through⁇ latest/edge channel does show latest update as of today (and 0+git.726c3c6 version), but in the application it still displays 2.5.0 and it seems that something rally doesn't seem to work. In the latest/stable, clicking either „Power metal” and „Power Metal” shows albums from only „Power metal” genre, and in the Artists menu it also shows „Power metal” albums even though the band is the same to the letter in both cases.~~

After changing the version to–and–fro about three times cataloguing has actually succeeded and it seems to work as intended, even without the settings menu for changing capitalisation (which was a petty wish I must say).

It still shows version 2.5.0 though.

**Comment by Feichtmeier** [comment]
> @Feichtmeier ~~I think the update did come through⁇ latest/edge channel does show latest update as of today (and 0+git.726c3c6 version), but in the application it still displays 2.5.0 and it seems that something rally doesn't seem to work. In the latest/stable, clicking either „Power metal” and „Power Metal” shows albums from only „Power metal” genre, and in the Artists menu it also shows „Power metal” albums even though the band is the same to the letter in both cases.~~
> 
> After changing the version to–and–fro about three times cataloguing has actually succeeded and it seems to work as intended, even without the settings menu for changing capitalisation (which was a petty wish I must say).
> 
> It still shows version 2.5.0 though.

Yes the version is only bumped when I make a new release (for Ubuntu I then release it to the stable channel) 

I'll add a setting for you. That's why I wanted you to check first
