### ISSUE TITLE
Playback Speed Setting Not Retained Between Sessions

### ISSUE THREAD

**Issue by BrianBlowtasky** [ubuntu-flutter-community/musicpod#1092]
Description:
When using MusicPod, the playback speed setting does not persist after closing and reopening the application. Users expect that their last selected playback speed should be remembered across sessions, but currently, it resets to the default speed each time the app is launched. Steps to Reproduce:

    Open MusicPod.
    Set the playback speed to a desired value (e.g., 1.5x).
    Close the application completely.
    Reopen MusicPod.
    Observe that the playback speed has reverted to the default (1x).

Expected Behavior:
The application should remember the last playback speed setting and apply it automatically upon reopening, allowing for a seamless listening experience. 
Actual Behavior:
The playback speed resets to the default value every time the application is reopened. 
Additional Context:
This issue affects user experience significantly, as many users prefer to listen to content at specific speeds regularly. Retaining this setting would enhance usability and satisfaction with the app. Suggested Solution:
Implement a feature that saves the user's last playback speed setting in the app's preferences or local storage, so it can be restored upon launching the application again. Thank you for your attention to this matter!

**Comment by Feichtmeier** [comment]
> Description:
> When using MusicPod, the playback speed setting does not persist after closing and reopening the application. Users expect that their last selected playback speed should be remembered across sessions, but currently, it resets to the default speed each time the app is launched. Steps to Reproduce:
> 
>     Open MusicPod.
>     Set the playback speed to a desired value (e.g., 1.5x).
>     Close the application completely.
>     Reopen MusicPod.
>     Observe that the playback speed has reverted to the default (1x).
> 
> Expected Behavior:
> The application should remember the last playback speed setting and apply it automatically upon reopening, allowing for a seamless listening experience. 
> Actual Behavior:
> The playback speed resets to the default value every time the application is reopened. 
> Additional Context:
> This issue affects user experience significantly, as many users prefer to listen to content at specific speeds regularly. Retaining this setting would enhance usability and satisfaction with the app. Suggested Solution:
> Implement a feature that saves the user's last playback speed setting in the app's preferences or local storage, so it can be restored upon launching the application again. Thank you for your attention to this matter!

Hi 👋 thanks for the issue, will fix

> This issue affects user experience significantly, as many users prefer to listen to content at specific speeds regularly

I highly doubt this but it's an easy fix nonetheless so will fix
