### ISSUE TITLE
Enable shuffle on an album with one track locks up UI

### ISSUE THREAD

**Issue by amugofjava** [ubuntu-flutter-community/musicpod#114]
If you play an album that contains only one track and then click the shuffle button, the music continues to play in the background but the UI locks up. I'm guessing there is an infinite loop triggered by this scenario as the fans on my PC rev up when the UI freezes.

**Comment by Feichtmeier** [comment]
> If you play an album that contains only one track and then click the shuffle button, the music continues to play in the background but the UI locks up. I'm guessing there is an infinite loop triggered by this scenario as the fans on my PC rev up when the UI freezes.

uh, that sounds bad :D thanks! checking this
