### ISSUE TITLE
Reaching the end of an album causes repeat from last clicked track

### ISSUE THREAD

**Issue by amugofjava** [ubuntu-flutter-community/musicpod#115]
When you get to the end of an album, rather than ending, Musicpod will go back to the last track you clicked on even with repeat off - unless I have miss-understood the repeat mechanism.

The easiest way to reproduce this is to click on the last track of an album. When Musicpod reaches the end of the track, it will start playing it again and repeat.

**Comment by Feichtmeier** [comment]
yeah bug as well :D
thanks!
quality issues :+1: :star: 

I fix this now as the intended function for this button is repeat-single track
currently repeat all is default for the album/podcast you select
