### ISSUE TITLE
HTML tags in podcast description shows as text

### ISSUE THREAD

**Issue by amugofjava** [ubuntu-flutter-community/musicpod#17]
When viewing podcast details, if the description contains HTML tags these are shown as plain text. It would be good if the tags could either be stripped out or the HTML rendered. I can recommend the [flutter_html](https://pub.dev/packages/flutter_html) package for rendering - it works really well.

![Screenshot from 2023-03-13 19-19-47](https://user-images.githubusercontent.com/5526902/224809634-bf485504-3b72-4172-acff-8721ecf4fda2.png)

This app is off to a great start and I'm really looking forward to seeing how it develops.

**Comment by Feichtmeier** [comment]
Thanks @amugofjava ! Will do as suggested
