### ISSUE TITLE
Support m3u & .pls

### ISSUE THREAD

**Issue by YamiYukiSenpai** [ubuntu-flutter-community/musicpod#19]
I saved some .m3u & .pls playlists and they aren't showing up.

**Comment by Feichtmeier** [comment]
@YamiYukiSenpai .m4a files should show up now

however playLISTS are a different topic. They should not show up in the middle of titles, albums or artist pages
however I could add a button to import an  playlist somewhere eventually. maybe in the add playlist page 🤔

**Comment by YamiYukiSenpai** [comment]
> hey should not show up in the middle of titles, albums or artist pages

Yup, I know.

**Comment by Feichtmeier** [comment]
Reference for me 
https://pub.dev/packages/m3u_nullsafe

**Comment by Feichtmeier** [comment]
https://pub.dev/packages/pls

**Comment by Feichtmeier** [comment]
@YamiYukiSenpai m3u playlist import is now in

will look at pls soon :)

https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/7b1abe94-cb04-478f-a0c4-f853680286e3
