### ISSUE TITLE
Search is broken + the songs can't find all of my music

### ISSUE THREAD

**Issue by YamiYukiSenpai** [ubuntu-flutter-community/musicpod#20]
The search appears to be totally broken as I think I would need to keep scrolling in order for the app to find the music I'm looking for

When I look up Taylor Swift:
![image](https://user-images.githubusercontent.com/13153124/224859946-09777034-607c-4aa2-8c53-1a4d615192b4.png)
![image](https://user-images.githubusercontent.com/13153124/224859980-5cc08b89-6280-4771-8eac-728a1590a4f6.png)

When I look  up Eminem:
![image](https://user-images.githubusercontent.com/13153124/224860187-4b382129-d612-4a1c-9ec6-49aff6d1b4af.png)
![image](https://user-images.githubusercontent.com/13153124/224860207-eda2ee69-5fa0-499c-8434-458b6afadba7.png)

Another example, I know one of my favorites, "All Too Well" should be here, but the app can't seem to find it.
![image](https://user-images.githubusercontent.com/13153124/224860410-ec18f9fe-3f0b-40ad-a163-1a97d42802cd.png)
![image](https://user-images.githubusercontent.com/13153124/224860501-e12f20ff-6be9-46ff-8208-75bff9e5b0c4.png)

**Comment by Feichtmeier** [comment]
Hi! Thanks for the issue your are absolutely right 👍
I will rework the search to let you search anything and then select what you wanted to look up (artist, song, album, playlist)

**Comment by Feichtmeier** [comment]
Hi @YamiYukiSenpai 
If you have time refresh the snap, I reworked the search 
![grafik](https://user-images.githubusercontent.com/15329494/226042224-13a674cf-b039-4695-a5f9-b9bc134b9c38.png)

**Comment by YamiYukiSenpai** [comment]
:-(

![image](https://user-images.githubusercontent.com/13153124/226134334-60c99f91-782d-4b5a-ac3f-ce59e386a02c.png)
![image](https://user-images.githubusercontent.com/13153124/226134341-7b7628aa-8095-4742-aeb8-b59b3cd28a8b.png)

**Comment by Feichtmeier** [comment]
Are you sure you have your Taylor swift music tagged? I can find all my artists

**Comment by YamiYukiSenpai** [comment]
> Are you sure you have your Taylor swift music tagged? I can find all my artists

In what way would they need to be tagged?
Also, it didn't find any of the songs by Eminem, just the ones where he was featured.

**Comment by Feichtmeier** [comment]
> > Are you sure you have your Taylor swift music tagged? I can find all my artists
> 
> In what way would they need to be tagged?
> Also, it didn't find any of the songs by Eminem, just the ones where he was featured. 

Currently this app searches the metadata of audios. I could eventually also look into the file name as a fallback if there is no metadata
If your audio files have metadata it should really work :) I didn't insert code to be rude to Taylor swift and Eminem fans xD

**Comment by YamiYukiSenpai** [comment]
> > > Are you sure you have your Taylor swift music tagged? I can find all my artists
> > 
> > 
> > In what way would they need to be tagged?
> > Also, it didn't find any of the songs by Eminem, just the ones where he was featured.
> 
> Currently this app searches the metadata of audios. I could eventually also look into the file name as a fallback if there is no metadata If your audio files have metadata it should really work :) I didn't insert code to be rude to Taylor swift and Eminem fans xD

Haha 😸
Would the fact that I have over 800 songs play a role in this?

**Comment by Feichtmeier** [comment]
No, shouldn't have any role

On Ubuntu you can that click audio files and see the metadata in one of those tabs

If you want to change them I recommend 
sudo apt install easytag

**Comment by YamiYukiSenpai** [comment]
![image](https://user-images.githubusercontent.com/13153124/226517896-55980758-2b24-46e3-a6e3-de53a1486f52.png)
Like this?

**Comment by Feichtmeier** [comment]
> ![image](https://user-images.githubusercontent.com/13153124/226517896-55980758-2b24-46e3-a6e3-de53a1486f52.png)
> Like this?

Yes. Hmm that's weird then if you still can't find her
I guess I need to buy some Taylor swift music 🎶😂 to test

**Comment by YamiYukiSenpai** [comment]
> I guess I need to buy some Taylor swift music notesjoy to test

totally worth it.
hits all the feels

She's a relaxing thought

**Comment by YamiYukiSenpai** [comment]
![image](https://user-images.githubusercontent.com/13153124/229978318-41e76248-940a-45a9-9d38-7076344324b8.png)
Nice to see the artist view.

The app still appears to not show all of my audio unfortunately :-(
![image](https://user-images.githubusercontent.com/13153124/229978570-a49b78a2-c37a-4323-9e6c-ab3e9c3c357d.png)

**Comment by Feichtmeier** [comment]
Which file format do they have?

**Comment by YamiYukiSenpai** [comment]
I got lists of bands/artists that are affected:
* Taylor Swift
* Eminem (only some, and all from 8-Mile album)
* The Beatles
* Metallica
* Hailee Stienfeld
* Backstreet Boys

**Comment by Feichtmeier** [comment]
@YamiYukiSenpai hey again :grin: 

Could you refresh the snap and try again? some stuff happened since april

**Comment by YamiYukiSenpai** [comment]
> @YamiYukiSenpai hey again 😁
> 
> Could you refresh the snap and try again? some stuff happened since april

Sorry! I missed this notification!  I'm currently trying it out, and it's stuck on loading.  I did force MusicPod to point to the current directory of my Music library.  Re-opening didn't help

**Comment by Feichtmeier** [comment]
The filter is for when you pin podcasts albums or radios

**Comment by Feichtmeier** [comment]
@YamiYukiSenpai 

[Bildschirmaufzeichnung vom 2023-08-21, 10-11-00.webm](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/6abeef93-c522-4e17-acab-15f6dee61a00)

similar to how spotify handles the sidebar

you can pin albums from the local audio, create playlists, star stations or sub to podcasts. all those things show up in your sidebar then. the filter pill helps to focus on one of the types

**Comment by Feichtmeier** [comment]
Made it jump to the left after selection

Will hide it if one didn't pin something at all

Thanks for the feedback

I'm interested why your music folder didn't load though
So you selected a different directory and what happened then?

**Comment by Feichtmeier** [comment]
@YamiYukiSenpai 

[Bildschirmaufzeichnung vom 2023-08-21, 20-45-44.webm](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/9ad6a3f4-a3f5-4697-9b3e-9af703d07701)


now the filter bar hides if you didnt pin anything
