### ISSUE TITLE
MusicPod can't read AAC files

### ISSUE THREAD

**Issue by JollyPanda** [ubuntu-flutter-community/musicpod#308]
My MusicPod install doesn't seem to read any of the AAC files I have. They don't appear on the list, nor can they be played by selecting MusicPod with right click on the file.

I have tried many different music players installed as Snap, Flatpak and native packages and none of the Snap music players are able to play back or even list the AAC files; but Flatpaks and native packages can, which makes me think maybe I need to install another package to make Snaps compatible with AAC.

**Comment by Feichtmeier** [comment]
hi
musicpod uses mpv under the hood to play audio. I think, even though I never heard of aac, mpv should be able to play aac.
For reading metadata, I am not sure if the package I use for reading metadata understands aac metadata. Does aac have metadata? 
Could you give me a link to a free aac file so I can play around with this a bit?

**Comment by JollyPanda** [comment]
Hello. According to [this thread](https://superuser.com/questions/1789216/i-cant-tag-my-aac-files-with-meta-data-what-can-i-do-instead) AAC files don't have mp3-style tags and other containers like m4a and mp4 carry those things instead. I remuxed some of my files to m4a using ffmpeg, added some tags and they can be played now.

Weirdly enough the original aac files can be played by mpv.

[Here are a few samples,](https://www.learningcontainer.com/sample-aac-file/)

**Comment by Feichtmeier** [comment]
Thanks!

Downloaded the sample and it shows up and song plays
![Bildschirmfoto 2023-11-29 um 12 45 49](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/906a5e28-60d2-4735-a075-c6f48cfc5b1b)

**Comment by JollyPanda** [comment]
Well, I tested those files and they worked. There must've been something wrong with my files then because they didn't appear until I converted them to m4a.

However the first sample file from [this website](https://getsamplefiles.com/sample-audio-files/aac) also doesn't seem to appear on my library when I add them to my music directory. I'm starting to think it's a user error though.
