### ISSUE TITLE
Make an Arm64 release

### ISSUE THREAD

**Issue by cjsmocjsmo** [ubuntu-flutter-community/musicpod#35]
I have Ubuntu 22.10 installed on my raspberry pi, I have flutter installed via snap packages.  Please release an arm64 version so people such as myself can enjoy your product.  Flutter is advertised as cross-platform so why only the amd64 download?

**Comment by Feichtmeier** [comment]
Sure thing, it should actually auto build for arm64, wondering what I am doing wrong 🤔

**Comment by 12people** [comment]
@Feichtmeier
It's probably this Flutter bug that keeps it from building on ARM on Linux right now: https://github.com/flutter/flutter/issues/116703
Unfortunately, it doesn't seem to be a high priority for the Flutter team.

**Comment by Feichtmeier** [comment]
Oh? Really? Hm, I thought it is rather related to the snapcraft infrastructure where you can describe  for what arch your snap should be built 🤔

**Comment by 12people** [comment]
It could be both :)
(I'm not familiar with how snaps work, so I can't help there.)

**Comment by peter-kal** [comment]
I might be mistaken but doesn't building an arm snap requires an arm machine or something?
https://forum.snapcraft.io/t/architectures/4972

**Comment by sergiusens** [comment]
If this is snapcraft that is blocking you, mind sharing a build log?

**Comment by Feichtmeier** [comment]
> If this is snapcraft that is blocking you, mind sharing a build log?

hi @sergiusens thanks 👋 

I specified the architectures here
https://github.com/ubuntu-flutter-community/musicpod/blob/main/snap/snapcraft.yaml#L15
But I have the feeling that I might did this wrong, because only the amd64 is beeing build:
<img width="1184" alt="grafik" src="https://user-images.githubusercontent.com/15329494/232219797-622685b4-110a-4f46-b2bf-4f842a380f80.png">

This is the last build's log:
https://launchpadlibrarian.net/660855254/buildlog_snap_ubuntu_jammy_amd64_96593b40addf490b9f602dfed7ecfdd9_BUILDING.txt.gz

**Comment by peter-kal** [comment]
Could this fix help ?
https://github.com/canonical/ubuntu-desktop-installer/pull/1527

**Comment by cjsmocjsmo** [comment]
Although #116703 is not closed, with this version of flutter : 

Flutter (Channel master, 3.11.0-18.0.pre.6, on Ubuntu 23.04 6.2.0-1004-raspi, locale en_US.UTF-8)

I can once again build my flutter apps, so you may want to run your build script again :)

**Comment by Feichtmeier** [comment]
The arm build triggers now but fails, log:

[buildlog_snap_ubuntu_jammy_arm64_96593b40addf490b9f602dfed7ecfdd9_BUILDING.txt.gz](https://github.com/ubuntu-flutter-community/musicpod/files/11688797/buildlog_snap_ubuntu_jammy_arm64_96593b40addf490b9f602dfed7ecfdd9_BUILDING.txt.gz)
