### ISSUE TITLE
Opus support

### ISSUE THREAD

**Issue by initiateit** [ubuntu-flutter-community/musicpod#353]
Hi There!

Firstly gotta say love the look of your app and thanks for your work.

I read the other post on AAC support and consequently how musicpod uses mpv under the hood. Is there any reason why opus files arent being recognised?

I am able to play them using `mpv filename.opus`

Thanks kindly.

**Comment by initiateit** [comment]
Here is a file with metadata:
[Opus File](https://drive.google.com/file/d/17SJ8OnraXhq-kXIqNpeE6CntTOTTMzlT/view?usp=sharing)

**Comment by Feichtmeier** [comment]
Thanks I'll check that
Eventually the edge build from last night might have fixed this because I've allowed more files to be loaded. 
But I'm not sure, need to see myself

**Comment by Feichtmeier** [comment]
okay the problem is not mpv, but the package I use for reading out metadata
it seems that opus uses Id3v2 which is not supported by metadatagod.dart
metadatagod says it supports mp3, m4a, ogg & flac, but that ogg file with opus codec seems not to work
I request this in the metadata got package

**Comment by initiateit** [comment]
@Feichtmeier thanks ever so much for looking into that. Appreciate it!

**Comment by damywise** [comment]
Seems like #60 is what actually broke this?
I tried using `metadata_god` and it was loading mine and @initiateit's opus files just fine.
![image](https://github.com/ubuntu-flutter-community/musicpod/assets/25608913/021fd50e-aa85-4747-9678-2a30be194fa3)

I'm guessing the problem is with `isValidFile` in `lib\utils.dart`, specifically `lookupMimeType`. It doesn't recognize opus files as audio, or anything. I just force it to return true if `path.endsWith('.opus')` and it just works.

**Comment by Feichtmeier** [comment]
> Seems like #60 is what actually broke this?
> I tried using `metadata_god` and it was loading mine and @initiateit's opus files just fine.
> ![image](https://github.com/ubuntu-flutter-community/musicpod/assets/25608913/021fd50e-aa85-4747-9678-2a30be194fa3)
> 
> I'm guessing the problem is with `isValidFile` in `lib\utils.dart`, specifically `lookupMimeType`. It doesn't recognize opus files as audio, or anything. I just force it to return true if `path.endsWith('.opus')` and it just works.

Thanks @damywise 

I'll investigate

**Comment by Feichtmeier** [comment]
@damywise @initiateit I've switched back to metadata god for the moment, until I've found a pure dart implementation that works for MP3, flac, ogg and opus
That's in stable and edge
Best regards

**Comment by damywise** [comment]
Heya, maybe it's missing `path.endsWith('.opus') ||` in `isValidFile`?
I see that you've added some extensions manually, but opus is not there. I checked on master and the 1.0.1 release build. It doesn't detect `.opus` files. Though, if overridden, the metadata does work.
Cheers
