### ISSUE TITLE
It doesn't import musics from child directories

### ISSUE THREAD

**Issue by bfapps** [ubuntu-flutter-community/musicpod#39]
Hi Dear Developers,
 On Ubuntu 22.10 and 23.04, It imports musics perfectly if my music directory has no child directory inside it. Unfortunately, it doesn't import musics from a child directory. For example, if I have two directories inside my music directory, it only imports musics which are outside those two folders. Please fix this issue or let me know if there is something wrong with my snap sandbox permissions. Many thanks in advance.

**Comment by Feichtmeier** [comment]
hi @bfapps 
I can not confirm this :thinking: 

But eventually the import broke because I didn't catch an import exception. This should be fixed now. Could you refresh the snap and try again? 
best regards

**Comment by bfapps** [comment]
Hi again,
It works now. The only problem is that I have to restart the app to apply the new settings. I'm fine by restarting it, though.
Thanks for fixing it.
Best wishes

**Comment by Feichtmeier** [comment]
> Hi again, It works now. The only problem is that I have to restart the app to apply the new settings. I'm fine by restarting it, though. Thanks for fixing it. Best wishes

oh then there is something wrong in the recent changes I made. 🤔  
will fix it to apply instantly (like it was last week)

**Comment by bfapps** [comment]
It works now. The only remaining problem is that it doesn't import musics which have no metadata. I can manually add metadata, but it could be better if we were able to import those musics using their names if they had no metadata, as well. I think this is another issue that is opened by another person. So I'll be looking forward to that, as well. Thanks again for the great work.

**Comment by Feichtmeier** [comment]
Okay 👌👌
