### ISSUE TITLE
don't create new queues each time

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu-flutter-community/musicpod#395]
## Current Behavior

Currently, the local audio is like, if you click on an audio, the rest of the indices after that audio is added to the queue. This creates a tiny little issue, for the audios before that song. For example, if I want to listen to the song at index: 2 after that song completes, my current option to do so, is just add that particular song to the queue next to the current from the left side heart button. 

## Proposed Behavior

For local audios, if we can add all the audios in the queue and play the audio index that's wished by the user, that'd be a great. So, users can navigate to any song whenever they want. Also, adds more songs for shuffling when shuffle is enabled.

https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/3d6509c4-2d1d-4527-85c1-13e35cab4c07

## Code Changes

To make the proposed behavior work, we'll need to update the `startPlaylist` function in `player_service` and add an optional index parameter, which will be of integer type. In the `audio_page_tile`, when calling the `startPlaylist` function, just provide the whole audio list and the index.

```diff

diff --git a/lib/src/common/audio_page_body.dart b/lib/src/common/audio_page_body.dart
index 63b8d09..fbcbe71 100644
--- a/lib/src/common/audio_page_body.dart
+++ b/lib/src/common/audio_page_body.dart
@@ -270,8 +270,9 @@ class _AudioPageBodyState extends State<AudioPageBody> {
                   startPlaylist: widget.audios == null
                       ? null
                       : () => startPlaylist(
-                            widget.audios!.skip(index).toSet(),
+                            widget.audios!,
                             widget.pageId,
+                            index: index,
                           ),
                   resume: resume,
                   key: ValueKey(audio),
diff --git a/lib/src/player/player_model.dart b/lib/src/player/player_model.dart
index 2172721..e633559 100644
--- a/lib/src/player/player_model.dart
+++ b/lib/src/player/player_model.dart
@@ -110,8 +110,9 @@ class PlayerModel extends SafeChangeNotifier {
 
   Future<void> playPrevious() async => await service.playPrevious();
 
-  Future<void> startPlaylist(Set<Audio> audios, String listName) async =>
-      await service.startPlaylist(audios, listName);
+  Future<void> startPlaylist(Set<Audio> audios, String listName,
+          {int? index}) async =>
+      await service.startPlaylist(audios, listName, index: index);
 
   Color? get color => service.color;
 
diff --git a/lib/src/player/player_service.dart b/lib/src/player/player_service.dart
index e381334..d68248f 100644
--- a/lib/src/player/player_service.dart
+++ b/lib/src/player/player_service.dart
@@ -338,9 +338,10 @@ class PlayerService {
     }
   }
 
-  Future<void> startPlaylist(Set<Audio> audios, String listName) async {
+  Future<void> startPlaylist(Set<Audio> audios, String listName,
+      {int? index}) async {
     setQueue((listName, audios.toList()));
-    _setAudio(audios.first);
+    _setAudio(audios.elementAt(index ?? 0));
     _position = libraryService.getLastPosition.call(_audio?.url);
     _estimateNext();
     await play(newPosition: _position);
     
```

**Comment by Feichtmeier** [comment]
Thanks for the proposal. How about we do this for all playlists

**Comment by soumyaDghosh** [comment]
Yes, we can do that to. You can assign this to me.

**Comment by soumyaDghosh** [comment]
Should I create the PR 1, that'll add support of this in the local audios? @Feichtmeier

**Comment by soumyaDghosh** [comment]
Thanks a lot! :tada:
