### ISSUE TITLE
Feature Request: Support drag and drop from File manager

### ISSUE THREAD

**Issue by Nightmayr** [ubuntu-flutter-community/musicpod#451]
When dragging a bunch of audio files from a directory in Nautilus to Musicpod, nothing happens. What I'd like to have happen for example is when I have created an empty playlist, I want to be able to populate that playlist by dragging files from a directory in the file manager over to Musicpod when on the playlist's page.

**Comment by Feichtmeier** [comment]
Thanks!

Luckily there seems to be a package for this I could use

https://pub.dev/packages/super_drag_and_drop

I'll investigate

**Comment by Feichtmeier** [comment]
@Nightmayr got it working for mp3s :) do you use mp3 or ogg/opus/flacs?
Otherwise I wait until the package adds those formats

**Comment by Feichtmeier** [comment]
[Bildschirmaufzeichnung vom 2024-03-11, 16-53-03.webm](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/e18a75bf-a8f2-4828-8089-2e62c32bd2c8)

**Comment by Nightmayr** [comment]
Hey thanks for adding this feature :), it does work for me when importing files I have in the m4a format (haven't tried others). The only issue is when I drag files from a folder containing around 300 files (totalling 6GB), musicpod will become unresponsive (window can't be dragged or interracted with, although any audio that was playing carries on playing) and CPU usage for musicpod climbs to 100% and consumes RAM rapidly while adding the files. Eventually the files do get added but musicpod can be unresposive for nearly 10 minutes.

Below is an example of the resources used by musicpod, which on a less powerful machine like a laptop with 8GB of RAM might cause it to freeze.
![image](https://github.com/ubuntu-flutter-community/musicpod/assets/24817147/cc4e0ef1-8dfa-43d8-a1b8-b0758b0c113a)

**Comment by Feichtmeier** [comment]
> Hey thanks for adding this feature :), it does work for me when importing files I have in the m4a format (haven't tried others). The only issue is when I drag files from a folder containing around 300 files (totalling 6GB), musicpod will become unresponsive (window can't be dragged or interracted with, although any audio that was playing carries on playing) and CPU usage for musicpod climbs to 100% and consumes RAM rapidly while adding the files. Eventually the files do get added but musicpod can be unresposive for nearly 10 minutes.
> 
> Below is an example of the resources used by musicpod, which on a less powerful machine like a laptop with 8GB of RAM might cause it to freeze or be killed by systemd-oomd.
> ![image](https://github.com/ubuntu-flutter-community/musicpod/assets/24817147/cc4e0ef1-8dfa-43d8-a1b8-b0758b0c113a)
> 

Holy moly.... Hmm 🤔
I guess I limit the amount then for the moment as I can't do much about this since it's an external package
Are you directories not under one music folder? Otherwise as a workaround or the normal thing I would suggest how to use it would be to select one single music directory in the settings
Musicpod then builds the library with artists/albums/genres 
Thanks for the feedback
