### ISSUE TITLE
Podcasts from French national broadcaster not working

### ISSUE THREAD

**Issue by symac** [ubuntu-flutter-community/musicpod#460]
I know that French national broadcaster is not always podcasts' tools friendly and they (force) push users to use their official app so that might explain why there is an issue with many of the most popular podcasts here in France. All their podcasts (radio names are France Inter, France culture for example) are showing on the podcast screen (you can search for "Affaires sensibles", "le code a changé", "soft power" ...) but when you click nothing happens, not even an error message.

Starting musicpod from the terminal to try to get more information does not change anything, I can't get any error message.

I understand that fixing issues with every provider would be quite complicated and might be beyond the scope of the software but at lease having an error message would be nice for users.

And keep up the good work, the software is already very nice and is now my default music player for radio & mp3, looking forward to find all my podcasts there to finish the move :)

**Comment by Feichtmeier** [comment]
hey :) thanks for your kind words

it looks like that this podcast has for some reason an empty feedurl 🤔 
Most of the french podcasts work for me here, so eventually this one just has an error on itunes?

**Comment by Feichtmeier** [comment]
> @Feichtmeier thanks for this quick reply. I don't have any apple device and have not checked but if I search for one of this podcast on apple's website (I assume they have the same datasource), I can listen to latest episodes : https://podcasts.apple.com/fr/podcast/affaires-sensibles/id912451024
> 
> And it is the same for other popular French shows like [LSD](https://podcasts.apple.com/fr/podcast/lsd-la-s%C3%A9rie-documentaire/id390167127) or [Les odyssées](https://podcasts.apple.com/fr/podcast/les-odyss%C3%A9es/id1469858852). 
> 
> I have not been able yet to find any of the [Radio France podcasts](https://www.radiofrance.fr/podcasts) that would work withing musicpod, when all of them seem to play on Apple's website. So I assume Radio France is blocking something somewhere, or asking Apple to not distribute information. As I have said, since some months Radio France is really pushing for their official app but I believe it is still possible to listen to podcasts outside of it as they display [rss feeds](https://radiofrance-podcast.net/podcast09/rss_13940.xml) on the [page show](https://www.radiofrance.fr/franceinter/podcasts/affaires-sensibles) of their website.
> 
> If you can identify what is blocking that would be nice to prevent them from showing in the list but from I understand it is another software that is fetching the data, so at least having a feedback within musicpod that the podcast has no episodes available or something like that would be nice.

Hmm I don't have an apple handy but I can check on the computer later

Meanwhile I've made the UI now properly show if a feed is empty with a notification

@amugofjava do you know if null feedurls could come from your library or is it just forwarded from RSS.dart?

**Comment by amugofjava** [comment]
Hi @Feichtmeier,

Trying this out, podcast_search throws an error if it gets a null field. I realise I am not handling this possibility and assume it will not be null. I need to fix that; however, there is no enclosure being returned for this pordcast and, unfortunately, the results you get back from the Apple web site don't always match what you'll get back from their API.

This is the URL podcast_search is sending:

[https://itunes.apple.com/search?term=Affaires%20sensibles&country=fr&limit=10&explicit=No&media=podcast&entity=podcast](https://itunes.apple.com/search?term=Affaires%20sensibles&country=fr&limit=10&explicit=No&media=podcast&entity=podcast)

And the JSON back:
```
{
	"resultCount": 1,
	"results": [
		{
			"wrapperType": "track",
			"kind": "podcast",
			"artistId": 140064169,
			"collectionId": 912451024,
			"trackId": 912451024,
			"artistName": "France Inter",
			"collectionName": "Affaires sensibles",
			"trackName": "Affaires sensibles",
			"collectionCensoredName": "Affaires sensibles",
			"trackCensoredName": "Affaires sensibles",
			"artistViewUrl": "https://podcasts.apple.com/fr/artist/france-inter/140064169?uo=4",
			"collectionViewUrl": "https://podcasts.apple.com/fr/podcast/affaires-sensibles/id912451024?uo=4",
			"trackViewUrl": "https://podcasts.apple.com/fr/podcast/affaires-sensibles/id912451024?uo=4",
			"artworkUrl30": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/63/70/8c/63708c3b-ed11-5d19-fa67-132f92e463f3/mza_8301076687401115427.jpg/30x30bb.jpg",
			"artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/63/70/8c/63708c3b-ed11-5d19-fa67-132f92e463f3/mza_8301076687401115427.jpg/60x60bb.jpg",
			"artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/63/70/8c/63708c3b-ed11-5d19-fa67-132f92e463f3/mza_8301076687401115427.jpg/100x100bb.jpg",
			"collectionPrice": 0.00,
			"trackPrice": 0.00,
			"collectionHdPrice": 0,
			"releaseDate": "2024-01-20T14:59:00Z",
			"collectionExplicitness": "notExplicit",
			"trackExplicitness": "cleaned",
			"trackCount": 59,
			"trackTimeMillis": 3354,
			"country": "FRA",
			"currency": "EUR",
			"primaryGenreName": "Culture et société",
			"contentAdvisoryRating": "Clean",
			"artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/63/70/8c/63708c3b-ed11-5d19-fa67-132f92e463f3/mza_8301076687401115427.jpg/600x600bb.jpg",
			"genreIds": [
				"1324",
				"26"
			],
			"genres": [
				"Culture et société",
				"Podcasts"
			]
		}
	]
}
```

The API is returning a collection URL back. I'll dig into this a bit more encase podcast_search is not constructing the URL correctly.

**Comment by Feichtmeier** [comment]
Thanks @amugofjava for your investigation and time 🙏

**Comment by amugofjava** [comment]
I've never used Apple Connect for podcasts, but from what I have read there is a checkbox in the UI that 'makes the podcast public'. If this is not checked, you do not get the `feedUrl` element which would explain why you can find it on the Apple website (i.e. not public outside Apple) but not via the API. More [here](https://mjtsai.com/blog/2021/04/23/itunes-podcast-directory-now-hiding-feed-urls/).

Not sure if this is deliberate by the podcaster or accidental.

It is available though via the PodcastIndex: https://podcastindex.org/podcast/1328489

**Comment by symac** [comment]
> Not sure if this is deliberate by the podcaster or accidental.
> 

As I said earlier, the broadcaster Radio France is actively pushing their official app, so I would not be surprised if it was deliberate.

**Comment by Feichtmeier** [comment]
@symac hi

thanks to @amugofjava podcast index option is available now in musicpod

but you need a key and secret from their website

Since musicpod is open source and run inside a snap container I currently have no option to insert this into the snap via github actions for both AMD64 and ARM so I wait for this

However podcast index is free and you can just create an account
then in the settings you can safe them
![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/1ff0cd03-e839-4dee-a36c-094b9ecc9aac)
restart and use them from then on
thanks everyone :)

**Comment by symac** [comment]
Thanks @Feichtmeier that works perfectly. Maybe just an UX suggestion : when looking at the settings, having a generic button to "Save settings" might be better. It took me two tries to understand that the tick at the right of the input was the way to save the data.

But I am currently listening to a podcast from the national broadcaster and it works fine, wouldn't have excepted a solution in only two weeks when I posted the issue to this repository, thanks for this nice software and quick resolution.
