### ISSUE TITLE
Currently MusicPod does not read metadata from FLAC.

### ISSUE THREAD

**Issue by PetrBalvin** [ubuntu-flutter-community/musicpod#495]
After the new release, MusicPod does not read metadata from FLAC. It does not sort artists, albums, or covers. Everything is unknown. There was no problem with this before the update. Very annoying, all my music is in FLAC format.

**Comment by Feichtmeier** [comment]
sorry about that
I switched from metadagod to id3tag lib because metadata god has a native dependency which is hard to test
also id3tag lib is faster and pure dart

I will work on re-adding flac support with https://github.com/zengkid/flac_metadata
Thanks for your patience

**Comment by PetrBalvin** [comment]
All right, thank you for the explanation.
