### ISSUE TITLE
Sorting order in album view

### ISSUE THREAD

**Issue by fsobolev** [ubuntu-flutter-community/musicpod#503]
Currently sorting in albums view looks like it's random. A setting to define the order would be useful (by album name; by artist -> by album name; by year -> by album name; ...)

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/117388856/8a4adff8-6288-4195-8687-9b17864b00ed)

**Comment by Feichtmeier** [comment]
Can I close this @fsobolev ?
