### ISSUE TITLE
Blank screen after install

### ISSUE THREAD

**Issue by cjsmocjsmo** [ubuntu-flutter-community/musicpod#54]
After installing the snap package on my raspberry pi 4 (arm64), and launching it with the desktop icon all i get is a blank screen, no controls nothing just a blank screen.

Ubuntu 23.04

**Comment by Feichtmeier** [comment]
@cjsmocjsmo Hi 👋 when you have time could you refresh the snap and check if this is fixed?

**Comment by cjsmocjsmo** [comment]
Sure :)

Performed:
sudo snap refresh musicpod

Launched the application with the desktop icon and this is what I get:

![Screenshot from 2023-06-25 05-30-37](https://github.com/ubuntu-flutter-community/musicpod/assets/8879432/af511738-ab9b-46e2-9d15-26c1ea645902)


snap info musicpod
name:      musicpod
summary:   Music, podcast and internet radio player
publisher: Frederik Feichtmeier
store-url: https://snapcraft.io/musicpod
contact:   https://github.com/ubuntu-flutter-community/musicpod
license:   MPL-2.0
description: |
  Play local audio files, browse podcasts online or listen to internet radio
  stations.
  
  The podcast and radio features do currently need internet access and thus
  the network-manager-observe permission is being used to display a
  disconnect from the internet in the user interface.
commands:
  - musicpod
snap-id:      sxdOSGRbzsWhPmGrkYYAs68rzieTrIiv
tracking:     latest/edge
refresh-date: today at 05:15 PDT
channels:
  latest/stable:    –                                   
  latest/candidate: –                                   
  latest/beta:      –                                   
  latest/edge:      0+git.b9fcb6f 2023-06-25 (143) 48MB -
installed:          0+git.b9fcb6f            (143) 48MB -

**Comment by cjsmocjsmo** [comment]
FYI on my x_86 machine musicpod installs and launches with not issues, so this is exclusive to the arm64 arch :)

**Comment by Feichtmeier** [comment]
> FYI on my x_86 machine musicpod installs and launches with no issues, so this is exclusive to the arm64 arch :)

Interesting! Thank you very much for investigating

@kenvandine do you have any hint what this needs to run on arm?

**Comment by cjsmocjsmo** [comment]
Not sure this will help but it satisfied my curiosity.  I cloned the musicpod repo and did:
cd musicpod
flutter run 

this is the out put on arm64: 
flutter run
"da": 30 untranslated message(s).
"de": 7 untranslated message(s).
"fr": 10 untranslated message(s).
"it": 30 untranslated message(s).
"nl": 7 untranslated message(s).
"ru": 9 untranslated message(s).
"sv": 32 untranslated message(s).
"zh": 10 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Resolving dependencies... (35.2s)
+ archive 3.3.7
+ args 2.4.2
+ async 2.11.0
+ base_x 2.0.0
+ boolean_selector 2.1.1
+ build_cli_annotations 2.1.0
+ cached_network_image 3.2.3
+ cached_network_image_platform_interface 2.0.0
+ cached_network_image_web 1.0.2
+ characters 1.3.0
+ clock 1.1.1
+ collection 1.17.2
+ colorize 3.0.0
+ connectivity_plus 4.0.1
+ connectivity_plus_platform_interface 1.2.4
+ convert 3.1.1
+ cross_file 0.3.3+4
+ crypto 3.0.3
+ csslib 0.17.3 (1.0.0 available)
+ dbus 0.7.8
+ desktop_notifications 0.6.3
+ dio 4.0.6 (5.2.1+1 available)
+ equatable 2.0.5
+ fake_async 1.3.1
+ ffi 2.0.2
+ file 6.1.4 (7.0.0 available)
+ file_selector 0.9.4
+ file_selector_ios 0.5.1+4
+ file_selector_linux 0.9.2
+ file_selector_macos 0.9.3
+ file_selector_platform_interface 2.6.0
+ file_selector_web 0.9.1
+ file_selector_windows 0.9.3
+ flutter 0.0.0 from sdk flutter
+ flutter_blurhash 0.7.0
+ flutter_cache_manager 3.3.0
+ flutter_html 3.0.0-beta.2
+ flutter_lints 2.0.1
+ flutter_localizations 0.0.0 from sdk flutter
+ flutter_rust_bridge 1.78.0
+ flutter_test 0.0.0 from sdk flutter
+ flutter_web_plugins 0.0.0 from sdk flutter
+ get_it 7.6.0
+ gtk 2.1.0
+ handy_window 0.3.1
+ html 0.15.4
+ http 0.13.6 (1.0.0 available)
+ http_parser 4.0.2
+ intl 0.18.1
+ js 0.6.7
+ json_annotation 4.8.1
+ lints 2.1.1
+ list_counter 1.0.2
+ logging 1.2.0
+ matcher 0.12.16
+ material_color_utilities 0.5.0 (0.7.0 available)
+ media_kit 0.0.11
+ media_kit_libs_linux 1.0.2
+ meta 1.9.1
+ metadata_god 0.4.1
+ mime 1.0.4
+ mime_type 1.0.0
+ mpris_service 1.0.0 from git https://github.com/alexmercerind/mpris_service at 3a4a72
+ nested 1.0.0
+ nm 0.5.0
+ octo_image 1.0.2
+ palette_generator 0.3.3+2
+ path 1.8.3
+ path_provider 2.0.15
+ path_provider_android 2.0.27
+ path_provider_foundation 2.2.3
+ path_provider_linux 2.1.11
+ path_provider_platform_interface 2.0.6
+ path_provider_windows 2.1.7
+ pedantic 1.11.1
+ petitparser 5.4.0
+ platform 3.1.0
+ plugin_platform_interface 2.1.4
+ podcast_search 0.5.5 from git https://github.com/Feichtmeier/podcast_search at ac2368
+ pointycastle 3.7.3
+ pool 1.5.1
+ process 4.2.4
+ provider 6.0.5
+ puppeteer 3.1.1
+ radio_browser_api 0.1.0+4 (1.0.0 available)
+ rss_dart 1.0.3
+ rxdart 0.27.7
+ safe_change_notifier 0.2.0
+ safe_local_storage 1.0.2
+ screen_retriever 0.1.6
+ shelf 1.4.1
+ shelf_static 1.1.2
+ shelf_web_socket 1.0.4
+ shimmer 3.0.0
+ sky_engine 0.0.99 from sdk flutter
+ source_span 1.10.0
+ sqflite 2.2.8+4
+ sqflite_common 2.4.5+1
+ stack_trace 1.11.0
+ stream_channel 2.1.1 (2.1.2 available)
+ string_scanner 1.2.0
+ synchronized 3.1.0
+ term_glyph 1.2.1
+ test_api 0.6.0
+ tuple 2.0.2
+ typed_data 1.3.2
+ ubuntu_service 0.2.3
+ uri_parser 2.0.2
+ url_launcher 6.1.11
+ url_launcher_android 6.0.36
+ url_launcher_ios 6.1.4
+ url_launcher_linux 3.0.5
+ url_launcher_macos 3.0.5
+ url_launcher_platform_interface 2.1.3
+ url_launcher_web 2.0.17
+ url_launcher_windows 3.0.6
+ uuid 3.0.7
+ vector_math 2.1.4
+ web_socket_channel 2.4.0
+ win32 5.0.4
+ window_manager 0.3.4
+ xdg_directories 1.0.0
+ xml 6.3.0
+ yaml 3.1.2
+ yaru 0.8.1
+ yaru_icons 1.0.4
+ yaru_widgets 2.4.1 from git https://github.com/ubuntu/yaru_widgets.dart at d92074
+ yaru_window 0.1.3
+ yaru_window_linux 0.1.3
+ yaru_window_manager 0.1.2
+ yaru_window_platform_interface 0.1.2
+ yaru_window_web 0.0.3
Changed 132 dependencies!
"da": 30 untranslated message(s).
"de": 7 untranslated message(s).
"fr": 10 untranslated message(s).
"it": 30 untranslated message(s).
"nl": 7 untranslated message(s).
"ru": 9 untranslated message(s).
"sv": 32 untranslated message(s).
"zh": 10 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Launching lib/main.dart on Linux in debug mode...
ERROR: /home/charliepi/.pub-cache/git/yaru_widgets.dart-d92074d9dfa37b1e2c2df43c3a218ca0953806c1/lib/src/widgets/yaru_toggle_button_layout.dart:34:10: Error: Expected 2 type arguments.
ERROR:     with SlottedMultiChildRenderObjectWidgetMixin<_YaruToggleButtonSlot> {
ERROR:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: /home/charliepi/.pub-cache/git/yaru_widgets.dart-d92074d9dfa37b1e2c2df43c3a218ca0953806c1/lib/src/widgets/yaru_toggle_button_layout.dart:85:10: Error: Expected 2 type arguments.
ERROR:     with SlottedContainerRenderObjectMixin<_YaruToggleButtonSlot> {
ERROR:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: /home/charliepi/.pub-cache/git/yaru_widgets.dart-d92074d9dfa37b1e2c2df43c3a218ca0953806c1/lib/src/widgets/yaru_toggle_button_layout.dart:33:7: Error: The type 'SlottedMultiChildRenderObjectWidgetMixin<_YaruToggleButtonSlot>' can't be mixed in.
ERROR: class _YaruToggleButtonLayout extends RenderObjectWidget
ERROR:       ^
ERROR: /home/charliepi/.pub-cache/git/yaru_widgets.dart-d92074d9dfa37b1e2c2df43c3a218ca0953806c1/lib/src/widgets/yaru_toggle_button_layout.dart:84:7: Error: The type 'SlottedContainerRenderObjectMixin<_YaruToggleButtonSlot>' can't be mixed in.
ERROR: class _YaruRenderToggleButton extends RenderBox
ERROR:       ^
ERROR: /home/charliepi/.pub-cache/git/yaru_widgets.dart-d92074d9dfa37b1e2c2df43c3a218ca0953806c1/lib/src/widgets/yaru_toggle_button_layout.dart:33:7: Error: The non-abstract class '_YaruToggleButtonLayout' is missing implementations for these members:
ERROR:  - RenderObjectWidget.createElement
ERROR:  - Widget.createElement
ERROR: Try to either
ERROR:  - provide an implementation,
ERROR:  - inherit an implementation from a superclass or mixin,
ERROR:  - mark the class as abstract, or
ERROR:  - provide a 'noSuchMethod' implementation.
ERROR: class _YaruToggleButtonLayout extends RenderObjectWidget
ERROR:       ^^^^^^^^^^^^^^^^^^^^^^^
ERROR: /home/charliepi/snap/flutter/common/flutter/packages/flutter/lib/src/widgets/framework.dart:1773:23: Context: 'RenderObjectWidget.createElement' is defined here.
ERROR:   RenderObjectElement createElement();
ERROR:                       ^^^^^^^^^^^^^
ERROR: /home/charliepi/snap/flutter/common/flutter/packages/flutter/lib/src/widgets/framework.dart:347:11: Context: 'Widget.createElement' is defined here.
ERROR:   Element createElement();
ERROR:           ^^^^^^^^^^^^^
ERROR: /home/charliepi/.pub-cache/git/yaru_widgets.dart-d92074d9dfa37b1e2c2df43c3a218ca0953806c1/lib/src/widgets/yaru_toggle_button_layout.dart:94:29: Error: The method 'childForSlot' isn't defined for the class '_YaruRenderToggleButton'.
ERROR:  - '_YaruRenderToggleButton' is from 'package:yaru_widgets/src/widgets/yaru_toggle_button.dart' ('/home/charliepi/.pub-cache/git/yaru_widgets.dart-d92074d9dfa37b1e2c2df43c3a218ca0953806c1/lib/src/widgets/yaru_toggle_button.dart').
ERROR: Try correcting the name to the name of an existing method, or defining a method named 'childForSlot'.
ERROR:   RenderBox? get leading => childForSlot(_YaruToggleButtonSlot.leading);
ERROR:                             ^^^^^^^^^^^^
ERROR: /home/charliepi/.pub-cache/git/yaru_widgets.dart-d92074d9dfa37b1e2c2df43c3a218ca0953806c1/lib/src/widgets/yaru_toggle_button_layout.dart:95:27: Error: The method 'childForSlot' isn't defined for the class '_YaruRenderToggleButton'.
ERROR:  - '_YaruRenderToggleButton' is from 'package:yaru_widgets/src/widgets/yaru_toggle_button.dart' ('/home/charliepi/.pub-cache/git/yaru_widgets.dart-d92074d9dfa37b1e2c2df43c3a218ca0953806c1/lib/src/widgets/yaru_toggle_button.dart').
ERROR: Try correcting the name to the name of an existing method, or defining a method named 'childForSlot'.
ERROR:   RenderBox? get title => childForSlot(_YaruToggleButtonSlot.title);
ERROR:                           ^^^^^^^^^^^^
ERROR: /home/charliepi/.pub-cache/git/yaru_widgets.dart-d92074d9dfa37b1e2c2df43c3a218ca0953806c1/lib/src/widgets/yaru_toggle_button_layout.dart:96:30: Error: The method 'childForSlot' isn't defined for the class '_YaruRenderToggleButton'.
ERROR:  - '_YaruRenderToggleButton' is from 'package:yaru_widgets/src/widgets/yaru_toggle_button.dart' ('/home/charliepi/.pub-cache/git/yaru_widgets.dart-d92074d9dfa37b1e2c2df43c3a218ca0953806c1/lib/src/widgets/yaru_toggle_button.dart').
ERROR: Try correcting the name to the name of an existing method, or defining a method named 'childForSlot'.
ERROR:   RenderBox? get subtitle => childForSlot(_YaruToggleButtonSlot.subtitle);
ERROR:                              ^^^^^^^^^^^^
ERROR: /home/charliepi/.pub-cache/hosted/pub.dev/yaru_icons-1.0.4/lib/src/widgets/yaru_placeholder_icon.dart:53:21: Error: The argument type 'BorderRadiusGeometry?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadiusGeometry?' is nullable and 'BorderRadiusGeometry' isn't.
ERROR:  - 'BorderRadiusGeometry' is from 'package:flutter/src/painting/border_radius.dart' ('/home/charliepi/snap/flutter/common/flutter/packages/flutter/lib/src/painting/border_radius.dart').
ERROR:       borderRadius: borderRadius,
ERROR:                     ^
ERROR: Target kernel_snapshot failed: Exception
Building Linux application...                                           
Exception: Build process failed

**Comment by Feichtmeier** [comment]
aha! yes very useful
this means that it is rather related to flutters arm support
I thought they merged the arm fix 🤔 
But eventually I need to either upgrade or use the dev channel

because this
```
ERROR: - RenderObjectWidget.createElement
ERROR: - Widget.createElement
ERROR: Try to either
ERROR: - provide an implementation,
ERROR: - inherit an implementation from a superclass or mixin,
ERROR: - mark the class as abstract, or
ERROR: - provide a 'noSuchMethod' implementation.
```
is weird

**Comment by Feichtmeier** [comment]
@Jupi007 do you have any under circumstances access to an ARM machine? Looks like our yaru widgets miss some implementations for ARM if I understand this correctly 🤔 ❓

**Comment by Jupi007** [comment]
@Feichtmeier sorry I only have x64 machines at home.
But I think @madsrh got a mac apple silicon.

**Comment by Feichtmeier** [comment]
@cjsmocjsmo by any chance.... does the issue still happen?

**Comment by madsrh** [comment]
> But I think madsrh got a mac apple silicon

Sorry for the (extremely) slow reply. I'm running the snap and it works just fine here. This is on the M1, I haven't tried the Pi.

**Comment by cjsmocjsmo** [comment]
My SD card crapped out and had to do a fresh system install (to include musicpod) and this is the results

Ubuntu 23.04
RPI 4
musicpod  0+git.393a6c7  286  latest/edge  frederik-feichtmeier

![Screenshot from 2023-07-20 06-21-22](https://github.com/ubuntu-flutter-community/musicpod/assets/8879432/a8c5e4ed-493b-4006-8953-e8c7cf994d6c)

**Comment by Feichtmeier** [comment]
Okay gonna emulate an ARM machine with qemu and see what's happening

**Comment by Feichtmeier** [comment]
@cjsmocjsmo sorry for the slow progress on the ARM problem, but I still did not manage to setup this with qemu. I fear I need to buy some sort of ARM machine for this.

I made a build with snapcraft online builds. If you have time would appreciate if you could test the new build from stable or edge, should be an update for your architecture

**Comment by cjsmocjsmo** [comment]
Ubuntu 23.04
musicpod                   0+git.5096fdf     533    latest/edge      frederik-feichtmeier  -

Sadly still the same blank screen.
Works great on my x86 machine.

![Screenshot from 2023-11-08 08-02-21](https://github.com/ubuntu-flutter-community/musicpod/assets/8879432/9ff119d0-bc61-482d-9b50-f212fff087bb)

**Comment by popey** [comment]
Musicpod works fine on arm64 here. (although I should file a bug for the weird squares, i guess).

I'm using revision 533 from the stable channel.

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/1841272/b7576248-c8ef-4741-a2f5-6873345b34be)

**Comment by Feichtmeier** [comment]
> Musicpod works fine on arm64 here. (although I should file a bug for the weird squares, i guess).
> 
> I'm using revision 533 from the stable channel.
> 
> ![image](https://github.com/ubuntu-flutter-community/musicpod/assets/1841272/b7576248-c8ef-4741-a2f5-6873345b34be)
> 
> 
> 

Thanks @popey 

This is great news

The characters missing is text where I used emojis.. Eventually for some reason fonts in flutter have an emoji problem on arm?
Could you check for example when you troll the search in radio and podcasts when you search for nonsense it should also show a page with emojis

**Comment by Feichtmeier** [comment]
I can not confirm this it runs fine on arm
