### ISSUE TITLE
Empty feed for Radio France's podcasts

### ISSUE THREAD

**Issue by MargauxM123** [ubuntu-flutter-community/musicpod#551]
For every podcast from Radio France the message "sorry this podcast's feed is empty" appears
Exemples: Affaires sensibles, le grand dimanche soir, le moment meurice, la série documentaire...

**Comment by Feichtmeier** [comment]
> For every podcast from Radio France the message "sorry this podcast's feed is empty" appears Exemples: Affaires sensibles, le grand dimanche soir, le moment meurice, la série documentaire...

hi!

Yeah this is something weird with the itunes provider and french podcasts
see #460 

I have added the option to use podcast index in the options that fixes this

When I find a way to add my own podcast index api key without loading it into git (-.-) I make it optional to use your own api key
