### ISSUE TITLE
Manual podcast subscription

### ISSUE THREAD

**Issue by DiogoConstantino** [ubuntu-flutter-community/musicpod#561]
Rationale:
Not all podcasts are on directories, and some aren't in any at all.
As is musicpod doesn't allow to subscribe podcasts using on it's RSS feed.

Request:
Add an option to paste a RSS feed into an input field to subscribe a podcast would be immensely useful and would bring musicpod a bit more to pair with most podcatchers.

Thank you!

**Comment by Feichtmeier** [comment]
@DiogoConstantino would you like to have such an option from within the sidebar (where add playlist is) or from the radio collection page?

**Comment by DiogoConstantino** [comment]
Sorry I haven't replied before, I've been very busy...
I've seen the merge and the result, I'm ok with it.
