### ISSUE TITLE
After the update, MusicPod doesn't read the metadata

### ISSUE THREAD

**Issue by PetrBalvin** [ubuntu-flutter-community/musicpod#563]
After the update, MusicPod doesn't read the metadata of around 80% of the music files in my library. All my music files are in FLAC format.

**Comment by Feichtmeier** [comment]
> After the update, MusicPod doesn't read the metadata of around 80% of the music files in my library. All my music files are in FLAC format.

That's unfornunate. All my MP3s and .ogg files work as before
I switched https://github.com/ClementBeal/audio_metadata_reader as it is much faster than metadatagod and easier to test
The flac support in there is quite new.
Is there any specific pattern you can see from the flac files that dont work?
Eventually try to reload the library

**Comment by PetrBalvin** [comment]
It looks like the metadata for some files cannot be read if the cover is attached.

**Comment by Feichtmeier** [comment]
@ClementBeal

Sorry for tagging you here, but do you have any idea why this might happen? I sadly dont have many flacs and for those I got everytrhing fine

**Comment by PetrBalvin** [comment]
I tried adding covers using MusicBrainz Picard and now it's fine. I usually use Tagger for editing metadata and adding covers, but that doesn't work now. Strange, the exact same file edited with Tagger works without any problem in HUAWEI Music on my phone and tablet and in Deepin Music on another of my computers.

**Comment by ClementBeal** [comment]
Hi everyone,

@PetrBalvin , could you please provide me some of your flac files? unfortunately, I don't have a lot of flac files and I wasn't able to tests all the possible cases.

Thank you :)

**Comment by PetrBalvin** [comment]
Of course, which one do you want, edited with Tagger or MusicBrainz Picard?

**Comment by ClementBeal** [comment]
Both would be nice!

**Comment by Feichtmeier** [comment]
@PetrBalvin any update on this? I didnt have this issue with my flacs

**Comment by Feichtmeier** [comment]
no response from op
for me flacs work fine
closing
