### ISSUE TITLE
Add provision manual radio links subscription

### ISSUE THREAD

**Issue by leefordjudes** [ubuntu-flutter-community/musicpod#574]
Add provision manual radio links subscription
like CustomRadioPlayer - Basic URL app
https://play.google.com/store/apps/details?id=de.battlestr1k3.radionerd

**Comment by Feichtmeier** [comment]
@leefordjudes would you like to have such an option from within the sidebar (where add playlist is) or from the radio collection page?

**Comment by leefordjudes** [comment]
Ok, that's good, or any good looking place in this app.

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/13608248/40b74a34-0baf-4002-a2f5-8c26f668e58f)

thank you for considering me.
