### ISSUE TITLE
Allow the local audio page audios to be sorted based on title

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu-flutter-community/musicpod#592]
I don't have any playlist, rather some handful of songs, and they are sorted randomly.. (not sure how). It'd be great if sorting based on title at least for the local audio page can be done.

Current scenario

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/ba108b15-1ed7-421a-8c86-e89cac8ee847)

**Comment by Feichtmeier** [comment]
All of your audio files look not tagged in the album field
The titles view is sorted by artist, album, then by track

I don't think this problem can be solved by sorting them by title. You should tag your audio files correctly

I won't add manual sorting for the titles view, sorry 

If anything for playlists, this is the only place were this makes sense 

Just use the search if you want to look for a specific track

**Comment by soumyaDghosh** [comment]
https://github.com/ubuntu-flutter-community/musicpod/blob/main/lib/src/local_audio/titles_view.dart#L35

Setting this line as `AudioFilter.tiltes` actually fixes it. Also, other mainstream music apps also seems to follow the same trend.

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/7dcec510-13d8-4aff-88e6-d74031a12d40)

Filtered based on titles

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/854284cc-452b-4664-99cc-01b56e32742f)

Filtered based on tracks

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/2f820c38-acf3-4517-91bb-e1b5701cec8e)

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/28091ae9-ea68-4a66-b68f-328642e97050)

**Comment by Feichtmeier** [comment]
I could change it permanently to be sorted by titles if you like. I don't use this view other than clicking anywhere and playing shuffle
That's it

**Comment by soumyaDghosh** [comment]
Thanks for your support, but, why not add an option in the settings under the Local Audio section, and let the users decide?

**Comment by Feichtmeier** [comment]
A setting is also fine, as long as you don't talk about a manual sort button in a potentially 1 000 000 000 long titles view :)
