### ISSUE TITLE
USB Drive as Music Source

### ISSUE THREAD

**Issue by Crocodile73** [ubuntu-flutter-community/musicpod#616]
Can you add the ability to set an external drive as the source of your music. So basically the root of the drive. I have all my albums under M:\. Musicpod just continues to look, but it doesn't actually access the drive. Also a sort order by name, year etc would be beneficial. This app so far is very good.

**Comment by Feichtmeier** [comment]
@Crocodile73 thanks for the issue! 
This is clearly something that needs to be fixed.
I think this is just https://snapcraft.io/docs/removable-media-interface
but then you need to manually allow this until musicpod be allowed to auto connct to that interface
Is this correct @soumyaDghosh and/or @kenvandine  ? (the snap experts :) )

**Comment by soumyaDghosh** [comment]
> @Crocodile73 thanks for the issue! 
> This is clearly something that needs to be fixed.
> I think this is just https://snapcraft.io/docs/removable-media-interface
> but then you need to manually allow this until musicpod be allowed to auto connct to that interface
> Is this correct @soumyaDghosh and/or @kenvandine  ? (the snap experts :) )

Probably not, because you'll not be given a path from portals, not a raw path. It'll be needed, only for OSs that don't have portals preinstalled.

**Comment by kenvandine** [comment]
It's probably worth adding the plug, I don't think portals will solve this as it provides individual paths to files.  I think there's discussion happening about allowing neighboring files but even if that's implemented it'll be quite a while before we can count on users having the appropriate version of portals.

**Comment by soumyaDghosh** [comment]
> I don't think portals will solve this as it provides individual paths to files.

I think it's working, and giving path to the folder, atleast for latest portals. But, yes, that would be definitely needed for old users.
![Screenshot from 2024-03-25 18-04-10](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/927268f2-b336-4961-9409-e9f5cd739a67)

And the musics are also showing up.

**Comment by Feichtmeier** [comment]
Ah I just saw that the snap already has removable-media plug
Try to turn this switch on and see if this helps
![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/b98a93ae-4909-4e3d-8a03-8924780baee0)

**Comment by Crocodile73** [comment]
Where do you access that page at?

**Comment by soumyaDghosh** [comment]
> Where do you access that page at?

Are you on Windows? It seems so from your comments.

**Comment by Crocodile73** [comment]
Yes sorry my mistake, I should of supplied you with more information. Yes windows.

**Comment by soumyaDghosh** [comment]
> Yes sorry my mistake, I should of supplied you with more information. Yes windows.

Yeah, then none of the above solutions will work for you.

**Comment by Feichtmeier** [comment]
oh..... okay I need to introduce the persmission plugin then
sorry ken/soumya for the noise

**Comment by Feichtmeier** [comment]
Hey I have managed to have a windows installation and a usb stick with music :)

I can _not_ confirm this.
Proof that it works (here):


https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/23d7d51b-2988-4d6f-b5f3-b2f72f1eb114

**Comment by Crocodile73** [comment]
I will look at this again tomorrow, and let you know. I have a large library, and gave it plenty of time originally. But let's see. What is your usb drive formatted under fat32?

**Comment by Feichtmeier** [comment]
> I will look at this again tomorrow, and let you know. I have a large library, and gave it plenty of time originally. But let's see. What is your usb drive formatted under fat32?

yes this one i formated for windows in fat32

**Comment by Crocodile73** [comment]
I'm thinking that maybe the issue for me. Checked my drive and its NTFS. Let's see if I can find another drive and format that in fat32 and try.

**Comment by Crocodile73** [comment]
I'll close this issue. As it works on a format of Fat32. If anyone stumbles across this in the future. Check or make sure it is Fat32 and not NTFS.
