### ISSUE TITLE
queueConfirmMessage duplicated in podcasts (dialog)

### ISSUE THREAD

**Issue by dmaliog** [ubuntu-flutter-community/musicpod#624]
queueConfirmMessage duplicated in podcasts (dialog)

![изображение](https://github.com/ubuntu-flutter-community/musicpod/assets/115931219/41f2370c-6944-4ee0-b8e1-50f59a029edb)

**Comment by dmaliog** [comment]
One text nested inside another

**Comment by Feichtmeier** [comment]
oh! thanks! will fix

**Comment by Feichtmeier** [comment]
its almost like a poem ... lol

**Comment by Feichtmeier** [comment]
apropos isnt 100 maybe a bit too low threshold? how about 300 ?
