### ISSUE TITLE
Feature Request: Change app language from settings

### ISSUE THREAD

**Issue by osopromadze** [ubuntu-flutter-community/musicpod#636]
I would like to have option to change app language. For example, I have system language set as English but want musicpod to be on Spanish.

**Comment by Feichtmeier** [comment]
Okay I see what I can do. Should be possible

**Comment by Feichtmeier** [comment]
> I can try to add this feature and create PR, is it ok for you?

I appreciate the initiative, but currently the settings are a home grown service, its very flexible and reactive but too complicated :P 
I see what I can do about it, will report if tested
