### ISSUE TITLE
Feature request: Retain volume level between application launches

### ISSUE THREAD

**Issue by popey** [ubuntu-flutter-community/musicpod#655]
:wave: Hello!

I frequently use MusicPod on my laptop for background music while I work. I *always* turn the volume down in the application to about 20%. Every time I reboot, I launch the application and have to turn the volume down. 

Can the application please retain the volume level between launches?

**Comment by Feichtmeier** [comment]
> :wave: Hello!
> 
> I frequently use MusicPod on my laptop for background music while I work. I *always* turn the volume down in the application to about 20%. Every time I reboot, I launch the application and have to turn the volume down. 
> 
> Can the application please retain the volume level between launches?

Hello there 
It should do this actually 
Added this some time ago 
Then it's a bug!
Will investigate:)
