### ISSUE TITLE
Feature Request: allow enabling/disabling of radio/local/podcast pages 

### ISSUE THREAD

**Issue by r0krwi** [ubuntu-flutter-community/musicpod#659]
Add a configuration option to disable or hide the radio and keep only the local function

**Comment by Feichtmeier** [comment]
> Add a configuration option to disable or hide the radio and keep only the local function

There's also podcast ;)

May I ask why the radio feature is distracting you? The code behind this is not triggered if the tab is not selected

There are also awesome radio stations out there :) check out "6forty radio"

Generally I don't want to over modularize this app and it is specifically designed as an app to all free APIs to consume music, radio and podcasts. So there is no reason to close this issue but I'll probably not implement this

**Comment by r0krwi** [comment]
I understand completely , thanks for your reply

**Comment by Feichtmeier** [comment]
> I understand completely , thanks for your reply

Maybe some time in the future, we'll see
Thanks for using MusicPod
