### ISSUE TITLE
Apple Music Search doesn't actually search

### ISSUE THREAD

**Issue by popey** [ubuntu-flutter-community/musicpod#660]
I'm listening to the radio, I wonder where I can buy this song, so I click the radio station album art, then click Apple Music Search (because I'm on a Mac today) and it launches Apple Music and leaves me in the search field.

I would expect it to at least fill the artist and song name in.

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/1841272/f1d5270d-37d4-4610-84fe-071eaa5a9ebb)

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/1841272/0deba89c-a6e5-4a1f-bfde-dd6bf5b0a738)

**Comment by Feichtmeier** [comment]
Hmm 🤔 
I think I checked this one from a Linux machine and then it leads to the web which should work
But it looks like I need to handle this differently for Mac's
Will investigate! Thanks

**Comment by popey** [comment]
Yup, just re-tested on my Linux machine, and it does indeed go to the default browser, showing an Apple Music web page such as:

https://music.apple.com/us/search?term=Let%20s%20Dance%20-%20David%20Bowie

**Comment by Feichtmeier** [comment]
![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/029bf9ee-bdef-4a82-b563-e4bc2ba1c80f)
hm.... it works here, any info I miss here?

**Comment by Feichtmeier** [comment]
https://github.com/user-attachments/assets/0470daa6-6a75-446a-8b22-af21c91504d1

@popey I think I understand whats your prob you needf to tab on "apple music"
