### ISSUE TITLE
Amazon (and Amazon Music) Search takes me to German Amazon

### ISSUE THREAD

**Issue by popey** [ubuntu-flutter-community/musicpod#661]
I'm sure Amazon in Germany is delightful, but I'm not there. If I click an Amazon logo, I would expect to go to a localised search.

<img width="1062" alt="Screenshot 2024-04-17 at 20 08 01" src="https://github.com/ubuntu-flutter-community/musicpod/assets/1841272/8ac214dd-b995-49c5-ad26-b3be675cb2db">

Takes me to:

https://music.amazon.de/search/Praise+You+-+Fatboy+Slim?filter=IsLibrary%7Cfalse&sc=none

Similarly the Amazon search goes to:

https://www.amazon.de/s?k=Praise+You+-+Fatboy+Slim&i=digital-music

**Comment by Feichtmeier** [comment]
Lol sorry
You don't want to shop at the AUTOBAHN?!?!
I'LL FIX THIS SORRY CAPS
