### ISSUE TITLE
Clipboard copy dialog disappears too quickly

### ISSUE THREAD

**Issue by popey** [ubuntu-flutter-community/musicpod#662]
If you click a track from the history of a radio station, a 'toast' popup appears at the bottom, letting you know it's been copied to the clipboard. There are also icons (links?) to each of the popular stores. If I move my mouse down there, to click on a store, I expect the toast to stay where it is. 

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/1841272/5c031f3f-7356-44a5-bd8d-d5d1d8f45e62)

Sadly it disappears very quickly, too quickly for me to hover along the list until I land on the one I want.

**Comment by Feichtmeier** [comment]
Sure I'll give more time :) thanks for the issue
