### ISSUE TITLE
Music controls don't make sense when streaming radio

### ISSUE THREAD

**Issue by popey** [ubuntu-flutter-community/musicpod#663]
The queue, shuffle, repeat, previous, next buttons make no sense when listening to a streaming station. It's even possible to toggle shuffle on/off but it has no effect (unsurprisingly). Further, the queue button pops up a dialog, but there's seemingly nothing you can do with the queue when streaming.

<img width="1216" alt="Screenshot 2024-04-17 at 20 30 13" src="https://github.com/ubuntu-flutter-community/musicpod/assets/1841272/fb106fa7-c606-4c96-95d2-da105d5316b2">

**Comment by Feichtmeier** [comment]
That's s valid point
I'll switch them away
