### ISSUE TITLE
I can’t figure out what translation is missing

### ISSUE THREAD

**Issue by dmaliog** [ubuntu-flutter-community/musicpod#665]
I can’t figure out what translation is missing :)
"ru": 1 untranslated message(s).

**Comment by dmaliog** [comment]
Is there any way to show this?  To quickly find and translate

**Comment by Feichtmeier** [comment]
sorry

its

  "ru": [
    "copyToClipBoard"
  ],

there is a flag i activated now, as soon as the PR is merged, pull :)
