### ISSUE TITLE
Feature request: add changing speed to the UI of the music library.

### ISSUE THREAD

**Issue by TheShadowOfHassen** [ubuntu-flutter-community/musicpod#688]
There is a bug, where if I change speed in my podcast the speed will stay changed, if I go to the radio or the local music and play something the speed will also be the changed speed. With the radio, it's a bit weird and might be need to be fixed. Maybe change it to reset the speed if you change from sources.

With the music, on the other hand, its actually kind of fun to listen to music on 2x speed. Could we add the speed UI element to the local music? I know there are two different ways to change music speed, one also changes the pitch and makes people sound like chipmunks, and the other just changes the speed. Currently, Muspod only changes speed, do you think it's possible to let the user chose either. There are settings in MPV to make it also change pitch, here: https://mpv.io/manual/master/ so I think it's technically possible.

Note while the first part, the bug report should probably be fixed eventually, but take your time with the feature request it's a very niche request, I'm certain most people don't want 2x speed music.

**Comment by Feichtmeier** [comment]
hey, I fixed the issue with the wrong rate after audio change so it is always again 1 when you change the audio (file/url)
however, UI-wise there is no more room for this and also it doesnt make sense for normal audio files. so this is a wont fix, sorry! <3
