### ISSUE TITLE
Feature Request: Add Random Playlist

### ISSUE THREAD

**Issue by cjsmocjsmo** [ubuntu-flutter-community/musicpod#69]
Having a Add Random Playlist button next to the playlist button would be very useful.  

This is the idea.  When you click the Add Random Playlist button a modal with 2 inputs (name, number of songs) and a Add button pops up.  When the form is filled out and the Add button is clicked MusicPod will generate a new playlist with however may random songs you requested from your local music collection.

Best Regards.

**Comment by Feichtmeier** [comment]
I have never see this functionality before but sure why not. Basically shuffle but with a fixed length of the list?

**Comment by Feichtmeier** [comment]
Okay this would be easy but I just do not understand the use case?
why not just use shuffle instead? especially since the size of ones local audio collections varies heavily.

**Comment by Feichtmeier** [comment]
IMO this makes no sense (no idea)
if you want shuffle, use shuffle
