### ISSUE TITLE
Bug: Radio streaming playhead wobble

### ISSUE THREAD

**Issue by popey** [ubuntu-flutter-community/musicpod#697]
When streaming radio, in the panel on the right, the play head keeps moving back and forth. It's kinda distracting.

Artists impression:

```
 06:31 =============================O---- 06:37
 06:32 ==============================O--- 06:38
 06:33 =============================O---- 06:39
 06:34 ==============================O--- 06:40
```

Using latest macOS build.

**Comment by CosmicRaptor** [comment]
https://github.com/ubuntu-flutter-community/musicpod/assets/60008842/42e137c3-88b1-4b7d-8909-86886714d365


I think I get why it is happening. The radio loads new chunks, which moves the slider back a little. If you pause, the slider continues moving back as new chunks are being loaded.

I don't know if this is intended behaviour.

**Comment by Feichtmeier** [comment]
@popey is this any better?

for duration < 30 seconds



https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/2a440b5a-0d1b-449e-9772-6885e0529a8f

**Comment by Feichtmeier** [comment]
for macos 

Uploading Bildschirmaufnahme 2024-05-12 um 19.28.25.mov…
