### ISSUE TITLE
Crash: musicpod killed by SIGABRT - org.freedesktop.gnomeAbrt

### ISSUE THREAD

**Issue by ejordan9** [ubuntu-flutter-community/musicpod#714]
musicpod closed unexpectedly

--- Running report_uReport ---
Error: Unable to open './coredump': No existe el fichero o el directorio

--- Se ha omitido collect_GConf ---
No se ha encontrado ninguna acción pertinente a este suceso.

--- Se ha omitido collect_vimrc_system ---
No se ha encontrado ninguna acción pertinente a este suceso.

--- Se ha omitido collect_vimrc_user ---
No se ha encontrado ninguna acción pertinente a este suceso.

--- Se ha omitido collect_xsession_errors ---
No se ha encontrado ninguna acción pertinente a este suceso.

--- Running analyze_CCpp ---
Generación de seguimiento
La traza inversa se ha generado y guardado, 104129 bytes
Can't open file 'component' for reading: No existe el fichero o el directorio

--- Running analyze_BodhiUpdates ---
Looking for similar problems in bugzilla

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/125694310/8ad13459-466c-4ada-bc60-468e5943ba7e)

**Comment by Feichtmeier** [comment]
Hi, is this the new flatpak)

**Comment by ejordan9** [comment]
> Hi, is this the new flatpak?

Is 46.1 Gnome Store

**Comment by Feichtmeier** [comment]
@ejordan9 does this still happen?

and do you use the snap or the flatpak?

**Comment by ejordan9** [comment]
Hi, yes, I get error every time I close the app, but it seems to me that it is Gnome that gives problems, sorry, I'm not very clear if it is snap or flatpak 
![image](https://github.com/ubuntu-flutter-community/musicpod/assets/125694310/3bf38a0c-9355-45dc-ac38-e24fc1f8c738)

**Comment by Feichtmeier** [comment]
not enough information, doiesnt happen for me, closing. re-open if this happens again, thanks!
