### ISSUE TITLE
Feature Request: Search by Artist, Album or Title

### ISSUE THREAD

**Issue by cjsmocjsmo** [ubuntu-flutter-community/musicpod#72]
Being able to search my collection by artist, or album or title would be very helpful.

First let me say I have 22,000 songs in my collection.  When you first launch MusicPod your collection is in alphabetic order.  Now if I want to play a ZZ Top song I have to scroll through 21,000 songs to view them.  Being able to search my collection by artist, album or title would make this a lot less painful.

Best regards

**Comment by Feichtmeier** [comment]
hmhm you can search by artist :)
you search for any searchquery and the searchpage then displays results for titles/artists/albums
are you on the latest version?

**Comment by Feichtmeier** [comment]
![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/becb7d18-f648-4fa9-a99e-281dc2606f68)

**Comment by cjsmocjsmo** [comment]
The output of snap list:

musicpod                        0+git.ac38f95               237    latest/stable    frederik-feichtmeier

The MusicPod I have installed looks nothing like the screenshot above, so yes I believe I'm running an older version ;}
So so sorry for the noise and  wasting your time

Best regards

**Comment by Feichtmeier** [comment]
No problem!
Not wasting my time
Curious why your snap does not auto update 
Did you disable auto update?
try
sudo snap refresh musicpod

**Comment by Feichtmeier** [comment]
but  0+git.ac38f95 should be the correct version
eventually the search icon is not visible enough and you did not find it? (really curious, there is a possiblity 🤷 )

**Comment by cjsmocjsmo** [comment]
Ok yea this is a little strange.  When I launched the program initially the search icon was not showing, I then went full screen and the search icon appeared, almost like it was hiding behind the left panel.  I then closed MusicPod and relaunched it several times to see if I could reproduce the behavior but I could not.  I then resized the app window to different sizes and the search icon appears to be reacting as expected.  Strange

But yea everything seems to be working now.  Thank you for your assistance.

As you can tell I've been using MusicPod, nice job :)

Best regards

**Comment by Feichtmeier** [comment]
Okay 👍 good to hear
Eventually I can improve the search bar discoverability

**Comment by Feichtmeier** [comment]
How is the performance with such a vaste local library?
Fyi: ogg is currently not supported for metadata, hopefully soon

**Comment by cjsmocjsmo** [comment]
Sorry it took so long to get back to you.  It's honey do season :) you know honey do this honey do that :)

As expected the initial run takes a while for it to index everything but after that it's very responsive. I was really surprised by how fast dart ran through everything. All I have are mp3's so not supporting ogg's really didn't affect me. Except for a few exceptions (add random playlist, not working on arm) I am very satisfied with my experience :)

I agree making the search icon a different color (or something) to make it stand out some may help people discover it easier :)

Best regards

**Comment by Feichtmeier** [comment]
Okay I made it a bit more white
![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/38a00eca-e7c3-4c9a-b3ce-10a505d5f878)

Hope this is enough?

**Comment by cjsmocjsmo** [comment]
Yes looks much better, thx :)
