### ISSUE TITLE
Progressbar has low contrast on OSX

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/musicpod#732]
This issue is both in the light and dark theme

<img width="699" alt="image" src="https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/c98299e9-8f42-40d5-8f92-0ad087696c50">

<img width="489" alt="image" src="https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/08696c31-062e-4bf6-a686-ef68e587f492">

**Comment by madsrh** [comment]
it actually looks like theres three colors used here 🤔 

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/e9d73f96-73f0-486e-b7e2-0e4492d366d7)

**Comment by Feichtmeier** [comment]
yes, the buffer
