### ISSUE TITLE
Increase volume slider knob contrast on popup

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/musicpod#733]
In the light theme, the slideknob should be colored

<img width="159" alt="image" src="https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/3842c499-53f9-41ff-b766-023f1cb3e74a">

**Comment by Feichtmeier** [comment]
you mean due to the bad contrast or in general?

**Comment by madsrh** [comment]
It is hard to see yes, but doesn't the knob always have color?

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/7158a93f-e949-4f50-979e-600a73e54f1b)

**Comment by Feichtmeier** [comment]
yes in full material 
but I diverged from it (hard divorce :D )
Maybe a stronger shadow?

**Comment by madsrh** [comment]
> Maybe a stronger shadow?

I think you need a thin light grey stroke or a very light grey background. Not sure the shadow would help much 🤷

**Comment by Feichtmeier** [comment]
> > Maybe a stronger shadow?
> 
> I think you need a thin light grey stroke. Not sure the shadow would help much 🤷 
> 
> 
> 

Okay! Yes the theming for flutter material widgets is sometimes super nice but at some it's very lacking. For sliders you don't have a border. But I have an idea how to get something similar will see next week
