### ISSUE TITLE
Align "search" icons in context menu

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/musicpod#734]
Would it be possible to add some padding? I know that the icons have a background on hover that aligns with the edge of the menu. Maybe it would look weird, but this jumps out at me. Also theres two hover backgrounds (the menu entry + the icon)

<img width="505" alt="image" src="https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/b096d528-a5ff-4226-9967-9dbc6af9bb19">

**Comment by Feichtmeier** [comment]
yes ofc, good catch
wasnt in that menu for quite some time :P 
eventually also some icons?
