### ISSUE TITLE
Vertical align now playing title

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/musicpod#735]
Not sure if this only applies to OSX

<img width="1032" alt="image" src="https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/e1281ab2-d2f5-4a9f-bffa-134d8d1a365c">

Should ofc be:
![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/ea4868bf-36b9-4b9e-a649-bf0cb854fec2)

**Comment by Feichtmeier** [comment]
One of the best songs of all time

But you didn't tag it correctly:P

That's why the artist is empty
Yeah sure I could set the fall back to ' ' or something but I'm the end this app needs the user to tag their lib on their own

**Comment by madsrh** [comment]
Ahhh, it's too late for issues today 😆 I think you misread the issue. It's about the placement of the text, not the text itself.

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/1e6fcc1e-a4e4-4cc0-aa49-85ecf172ffbf)

**Comment by Feichtmeier** [comment]
Yes when you have an artist name it's aligned correctly
