### ISSUE TITLE
Menu hidden when update is available 

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/musicpod#736]
I wonder if it is by design that the menu is gone when there's an update available? Maybe you want users to stay on the latest version 😊 

<img width="282" alt="image" src="https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/6b2d67bb-b0ff-4a37-b720-ca2940fecee2">

**Comment by Feichtmeier** [comment]
> I wonder if it is by design that the menu is gone when there's an update available? Maybe you want users to stay on the latest version 😊 
> 
> <img width="282" alt="image" src="https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/6b2d67bb-b0ff-4a37-b720-ca2940fecee2">
> 

Yes it's by design xD but I'm not super sure about it
In fact I thought about putting the settings entry back to the side panel even if I might go to gnome hell then

**Comment by Feichtmeier** [comment]
So meanwhile, what would you suggest? Want to be able to view both settings and update button?

**Comment by madsrh** [comment]
> Want to be able to view both settings and update button?

Indeed. Here's a few ideas. A poor but simple solution, just move the update icon next to the menu:

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/8ed8e4bf-365c-4476-af74-a0e70fe59134)


Does the app check for updates periodically while running or does it only check when the app is launched? You could add a pop up window. I saw this idea for some mobile app:

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/c94a9bad-e1f7-423a-bc29-3b3d00c62914)


Or add an entry to the sidebar:

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/07d1e79a-40a8-4d8e-a774-c36051be4e93)


A bit more annoying:

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/4bb6727b-3d93-4fb2-bcb4-96dffe452f92)

**Comment by Feichtmeier** [comment]
Nice mock ups! 

It checks at app start and when one opens the settings

How about moving the settings (back) to the sidebar and the update icon could then stay where it is?

**Comment by madsrh** [comment]
> How about moving the settings (back) to the sidebar and the update icon could then stay where it is?

So simple 🥇  Perfect!

**Comment by Feichtmeier** [comment]
okay! will do next week (for next release 🙈 , people that dont like many updates might be pissed)

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/d7008ea8-f36b-4e11-a650-650187f4203c

@madsrh WDYT?

**Comment by madsrh** [comment]
This is good 👍 

Is it maybe a bit easy to miss? It was a bit easier to spot at the top, but it makes sense to have this next to settings.

I'm happy with this draft.
