### ISSUE TITLE
"Open" favorites doesn't work in fullscreen 

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/musicpod#737]
Clicking _Open_ in fullscreen doesn't actually do anything. 

Shoudn't this label also be `colorScheme.primary`?

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/ac6de5d2-6173-44be-8afd-fb493ea3d979)

**Comment by Feichtmeier** [comment]
What happened before this toast popped up

**Comment by madsrh** [comment]
> What happened before this toast popped up

Sorry, I clicked the heart


<img width="293" alt="image" src="https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/bf8f2717-f005-4989-a254-4a40ada34721">
