### ISSUE TITLE
Request: add elapsed time

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/musicpod#753]
How about doing something like this? The time is visible when hovering the progressbar, but it would be nice to have in on screen all the time in a subtle grey.

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/b9b3848e-43ce-4404-82da-756c1755c514)

EDIT: ofc for podcasts as well

**Comment by Feichtmeier** [comment]
two reasons why I didnt include this in the latest iteration of the bottom player
1) there is not enough space when thre are all controls visible and you make the window more narrow
2) there is the full screen player if you want this information
personally I like to keep the bottom player more minimal, we can keep it open to see what others think

**Comment by madsrh** [comment]
> there is not enough space when thre are all controls visible and you make the window more narrow

I know. I was thinking this as a media query / responsive layout, so only when the window is really wide. I've seen the same done for the volumeslider when there is enough space. OFC this mockup looks a bit right-side heavy because the player controls isn't centered.

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/96006e35-52f2-45fb-88f0-b32093312009)

> personally I like to keep the bottom player more minimal, we can keep it open to see what others think

+1

**Comment by Feichtmeier** [comment]
At this stage it should switch to the sidebar mode (1200) I think. I can try it to play around with the idea

**Comment by Feichtmeier** [comment]
@madsrh 

how is this instead?

<img width="961" alt="grafik" src="https://github.com/user-attachments/assets/60350221-aea2-4112-94df-871e6f2c0b8b">

**Comment by Feichtmeier** [comment]
@madsrh I dislike is so much that I added a setting for it which is disabled by default ^^ 
but if you want it just for you <3

https://github.com/user-attachments/assets/01a363bb-a0de-4335-9ceb-b5e10ca73225

**Comment by madsrh** [comment]
> also... please tagg your music library

LoL 😆 

This look great. 

> ...which is disabled by default

Everybody wants this, they just didn't know it.
