### ISSUE TITLE
Country-menu is too narrow

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/musicpod#758]
<img width="426" alt="image" src="https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/e4cf204d-030a-4d74-ba9e-2a4eb0e10f4c">

I don't think the line break is a good idea. If you want the same width as the searchfield, IMHO you should ellipsis the text and ofc have it in the tooltip.

Side question: Are the star icons too big? Does it have the same size as this one? 
<img width="101" alt="image" src="https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/423d047c-6853-4f9a-bfbd-81bb2dae3889">

I would prefer the wider dropdown:

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/3986894/80407265-2496-414e-8c11-f2daea9a908d)

**Comment by Feichtmeier** [comment]
I feel like the text in all popups is too big in general
Yeah that star looks too big

**Comment by Feichtmeier** [comment]
@madsrh fix inc

could you create an issue for unifying all context menu and popup text sizes / icon sizes with sizes in a mockup you think would fit best for both macos and linux?

**Comment by madsrh** [comment]
You're back @Feichtmeier ! 🥳

I can, if it isn't time-sensitive. I'm a bit AFK this week.

**Comment by Feichtmeier** [comment]
Sure No hurry
