### ISSUE TITLE
Cover art doesn't show up for most of my music.

### ISSUE THREAD

**Issue by rago666** [ubuntu-flutter-community/musicpod#768]
[1920 Evil Returns - Original Motion Picture Soundtrack.tar.gz](https://github.com/ubuntu-flutter-community/musicpod/files/15413536/1920.Evil.Returns.-.Original.Motion.Picture.Soundtrack.tar.gz)
[Ek Je Chhilo Raja - Original Motion Picture Soundtrack.tar.gz](https://github.com/ubuntu-flutter-community/musicpod/files/15413548/Ek.Je.Chhilo.Raja.-.Original.Motion.Picture.Soundtrack.tar.gz)
![Screenshot_20240523_135758](https://github.com/ubuntu-flutter-community/musicpod/assets/51720144/0ad9312f-cf3e-4b39-b0a7-194f8a5077c7)

Cover doesn't show up on 1st archive(1920) but does on 2nd zip(Ek Je Chhilo)

**Comment by Feichtmeier** [comment]
HI :) 
I won't download your zip files but what audio format are those files?
best regards

**Comment by rago666** [comment]
All are mp3.

**Comment by TheShadowOfHassen** [comment]
Is the album art baked into the mp3's or is it  just in the folder? Musicpod doesn't pick up the art unless its set in the music metadata (I think)

**Comment by rago666** [comment]
@Feichtmeier @TheShadowOfHassen All metadata are embedded in the mp3s. You can check the files. I am not sharing virus, LOL.

**Comment by Feichtmeier** [comment]
Hm very weird, I don't have this problem with any of my MP3s :S also checked on multiple machines

could you upload a screenshot of the image info in the tag application that you use?
I will not download your zip : D

**Comment by TheShadowOfHassen** [comment]
I think what @Feichtmeier means, is that we don't think you're trying to infect us, but it's technically piracy for us to download copyrighted music without paying for it... 

What operating system are you using?

**Comment by rago666** [comment]
Sorry for the delay, was very busy. It was indeed a problem with the tagging program, I was using eartag, when I use tagger cover art works. Closing this, sorry for wasting your time. Have a good day.

**Comment by Feichtmeier** [comment]
> Sorry for the delay, was very busy. It was indeed a problem with the tagging program, I was using eartag, when I use tagger cover art works. Closing this, sorry for wasting your time. Have a good day.

Thanks for the reply! Nice that it works 🥂
