### ISSUE TITLE
Don't repeat single queue items automatically

### ISSUE THREAD

**Issue by symac** [ubuntu-flutter-community/musicpod#774]
When listening to a podcast, at the end of an episode, musicpod is currently starting again the same episode.
That would make more sense to jump to the next episode of the podcast I believe.

**Comment by Feichtmeier** [comment]
> When listening to a podcast, at the end of an episode, musicpod is currently starting again the same episode. That would make more sense to jump to the next episode of the podcast I believe.

Hi! 

If you want to listen to the whole podcast you need to press the big button or on the context menu add to queue 

But the that it auto replays always the single episode is not good. I'll fix that

**Comment by Feichtmeier** [comment]
![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/c7a48d5c-f8d5-4865-9b20-26f9ff36f110)
![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/f75b1d91-6650-42fa-a62a-0f17e69f383e)
