### ISSUE TITLE
Podcasts with multiple episodes simply repeat the same episode after playback is finished

### ISSUE THREAD

**Issue by rolandixor** [ubuntu-flutter-community/musicpod#776]
_Apologies for writing multiple issues at once - I know you have a lot of issues to track down and fix. Only reporting this because I believe in this app and would love to see it become a robust option for the Linux desktop._

As mentioned in the title, when listening to a podcast with multiple episodes, the same episode simply repeats after playback is finished. Since there's no "previous" or "next", there's also no way to quickly change the episode without having to manually play it.

**Comment by Feichtmeier** [comment]
You need to press the big button at the top
