### ISSUE TITLE
Create a queue for everything and show queue in player view

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu-flutter-community/musicpod#78]
In the player within the app and in the mpris, when the next or the previous button is pressed, it doesn't take us to the next or the previous song. I think this is a major issue. Also, the app doesn't autoplay the next song when one ends. Kindly fix it.

**Comment by Feichtmeier** [comment]
hi @soumyaDghosh I can not confirm this

to enqueue more things you need to click on the big buttons
like for example
![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/ad1a1fd1-93bb-4f34-9cee-f60786937012)
or here
![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/42c01324-b291-4106-920b-4e9f11ac6bab)

when you start the app, search for a title and click it even if it is inside an album there is no way to know which songs you wanted to enqueue

if you are in an album/podcast use the big bad button at the top
![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/0c323de9-5026-4d75-9653-1cfd64626ab3)

**Comment by soumyaDghosh** [comment]
[Screencast from 2023-07-22 20-59-59.webm](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/04827d65-0e51-4f58-a441-486ca90b43ea)


I actually wanted to say this. Making queue and all is a whole different story. Also, I can't enqueue a single track. Logically, this app should play tracks one by one, if a single track is selected to play. If I'm wrong, please explain me about it.

**Comment by Feichtmeier** [comment]
OK I'll add the queue button and if you only play one song and never played an album/podcast with the big button it will create a queue. Every next single click should keep the queue then.
Maybe I can fix it today, already working on it

**Comment by soumyaDghosh** [comment]
Thanks for that! That's fast

**Comment by Feichtmeier** [comment]
@soumyaDghosh refresh your snap :) best regards

**Comment by soumyaDghosh** [comment]
Hi, that's a nice one, but I guess I was not able make you understand the problem. Generally, in a music player, playing a single track, the player should take on the local tracks list as the playlist and should play on. Just like here in g4music.

[Screencast from 2023-07-23 11-36-42.webm](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/45a1fab2-ac32-42d6-a901-eedb04bd71a1)
