### ISSUE TITLE
Not Opening (Windows)

### ISSUE THREAD

**Issue by Crocodile73** [ubuntu-flutter-community/musicpod#787]
Anyone else have an issue with 1.4.4 it's not opening for me. Had to revert to 1.4.3

Running Windows 11 23H2

**Comment by cristiangranero90** [comment]
Hello! Same situation here. It's not opening in Windows 11 22H2.

**Comment by Feichtmeier** [comment]
Hey guys, I am trying to get this working for you, need to set up a new windows machine first
hope the 1.4.3 is functional

**Comment by Feichtmeier** [comment]
Hey guys, 1.4.5 is out and should work
please report if it worked or not
best regards

**Comment by Crocodile73** [comment]
1.4.5 works for me now. One odd thing i noticed is my library shows 1 extra album blank cover for some reason. I have 51 albums. 51 show with covers, then 1 extra. No play icon. ;0)

**Comment by Feichtmeier** [comment]
> 1.4.5 works for me now. One odd thing i noticed is my library shows 1 extra album blank cover for some reason. I have 51 albums. 51 show with covers, then 1 extra. No play icon. ;0)

cool! I guess you have an untagged title in your lib and musicpod created an unknown album or something :P 
Closing this issue then thanks for the answer
