### ISSUE TITLE
Feature Request: Add support to play youtube video as audio

### ISSUE THREAD

**Issue by leefordjudes** [ubuntu-flutter-community/musicpod#794]
Feature Request: Add support to play youtube video as audio

This URL plays youtube video link as audio
https://www.ravbug.com/yt-audio/?v=7yl11rZOa64

**Comment by Feichtmeier** [comment]
Hi 👋 

YouTube is tempting feature, but I keep this out of MusicPod because I want to stay as legal as possible :) 
YouTube is always a risky thing legal wise, let alone their constant api changes. So, sorry to say this but I won't do it (in musicpod, maybe some day in a youtubemusic app?)
