### ISSUE TITLE
take on the local tracks list as the playlist and should play on

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/musicpod#84]
Hi, that's a nice one, but I guess I was not able make you understand the problem. Generally, in a music player, playing a single track, the player should take on the local tracks list as the playlist and should play on. Just like here in g4music.

[Screencast from 2023-07-23 11-36-42.webm](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/45a1fab2-ac32-42d6-a901-eedb04bd71a1)

_Originally posted by @soumyaDghosh in https://github.com/ubuntu-flutter-community/musicpod/issues/78#issuecomment-1646756349_

**Comment by Feichtmeier** [comment]
Well, I think this depends on how you listen to music, since when I open an album I always press the big button :laughing: 
but I think I can fix it for you

**Comment by soumyaDghosh** [comment]
Thanks, I actually don't listen to albums in general, but I have a huge list of songs, which are in my hdd. I use to play from them. And it's a case for lot Ig.

**Comment by Feichtmeier** [comment]
@soumyaDghosh :recycle: refresh the snap :smile_cat:

**Comment by soumyaDghosh** [comment]
Yup... now it's almost there. And I'd like to complete this. Now, the next button works, but not the previous button, the previous button should play the previous song of the song that's now playing. Also, that behavior should work when pressed twice, and on single click, the app should play the current song from starting.
