### ISSUE TITLE
false advertising 

### ISSUE THREAD

**Issue by allanlaal** [ubuntu-flutter-community/musicpod#853]
dont advertise this as am Android player, when that part is still WIP

**Comment by Feichtmeier** [comment]
i'll attach an apk at the next release

**Comment by srfsh** [comment]
> i'll attach an apk at the next release

Not trying to be rude here, but you actually didn't. According to the release dates, twice "next releases". This is just contributing to the view that this is false advertisement. This either requires this issue to be re-opened (with a title change if you feel offended) or the advertisements to be removed.

**Comment by Feichtmeier** [comment]
> > i'll attach an apk at the next release
> 
> Not trying to be rude here, but you actually didn't. According to the release dates, twice "next releases". This is just contributing to the view that this is false advertisement. This either requires this issue to be re-opened (with a title change if you feel offended) or the advertisements to be removed.

I've updated the description so you see it's not ready yet. 
Also if you have a certain feature high on your prio, hit the sponsor button. 
Always remember I do this for free here ;)
Enjoy MusicPod and
Best regards
