### ISSUE TITLE
mpris doesn't shows proper audio title and author on startup

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu-flutter-community/musicpod#87]
If I start to play the song which was last playing, just after opening the app for the first time, the mpris of the app will not show the title and author properly. But, when I again click the song, it shows it properly.

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/676a11ef-5165-4915-8caf-45afdee14282)
![image](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/8f7aea3c-daf1-4cb0-b9e3-563372afbf09)

**Comment by Feichtmeier** [comment]
@soumyaDghosh :arrow_down: refresh snap :laughing:

**Comment by soumyaDghosh** [comment]
man!!! you're taking too much pressure on you
