### ISSUE TITLE
No way to clear play queue?

### ISSUE THREAD

**Issue by rolandixor** [ubuntu-flutter-community/musicpod#882]
This one is a bit hard to describe, but I'll try my best.

I've noticed that after searching for and playing one selection of music, like say if you type in the name of an artist and play some songs from that search, this becomes the preset "playlist" that the player will play from no matter what you search for afterwards. So for instance, if you type in "Blues" and listen to some songs from that selection, and later type in "Jazz" and play one song from that selection, it doesn't move to the next song in "Jazz" once that song is completed. Rather it plays whatever was found and played in "Blues" before.

There seems to be no way to clear the play queue and start fresh. Am I making sense?

**Comment by Feichtmeier** [comment]
i have read this 10 times and i have no idea whatr you mean

there is a button "add to queue" when you hover a tile, does this help?

**Comment by rolandixor** [comment]
No, that's not what I'm referring to.

If I search for "Blues", play Blues 1, Blues 2, then Search for Jazz, and play Jazz 1, I'd expect the song that automatically plays next to be Jazz 2 (since it's what I've searched for). Instead, Blues 3 will play once Jszz 1 finishes.

**Comment by Feichtmeier** [comment]
where are you searching? local audio? radio? and what do you click? a title?

**Comment by Feichtmeier** [comment]
https://github.com/user-attachments/assets/0b23b097-d56f-441e-8a0d-c67ac08b27c9

**Comment by rolandixor** [comment]
I'll test again and see if this is still occurring for me. It was when I'd
reported this, but I have since then been so busy I haven't had much time
to check up on it.

As for where I was searching, in the local library

**Comment by Feichtmeier** [comment]
sure, I think you search for "jazz" but then you clicked a title that was named somewhere with "jazz", this is however not the genre "jazz" which would be findable under the genre tab, so i guess this is a non-issue

**Comment by rolandixor** [comment]
I will test again when I get some time and let you know if the issue
persists. It's not related to genres, though. I used these terms since
they're familiar.
