### ISSUE TITLE
Idea: efficient use of the `previous` button

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu-flutter-community/musicpod#89]
Currently, when playing a playlist, the previous button takes to the previous song, of that playlist. But, what if when a single song is clicked from the tracks list of Local Audio, the next button now plays the next song, but how about adding the feature, when the previous button is pressed, in that scenario, the previous song will be played. If, it's the first song, then the last song from the local audio list can be played. Or, in that case, nothing can be done. Also, how about, when the previous button is pressed, the song that's playing currently will again play from the starting. And when pressed twice, the previous song will be played.

**Comment by Feichtmeier** [comment]
fixedby you:)
