### ISSUE TITLE
Dependance on Network Manager

### ISSUE THREAD

**Issue by izobilje** [ubuntu-flutter-community/musicpod#894]
Hi and thanks for developing!

I have a custom GNU/Linux setup and I don't use Network Manager to connect to the Internet. Musicpod was working just fine for me a few versions ago. Now in version 1.8.1, it complains about having no network connection. In the terminal output, it says _The name org.freedesktop.NetworkManager was not provided by any .service files_ . So I have to start the Network Manager for it to work. Can there be an option to disable this check, or can it be avoided?

**Comment by Feichtmeier** [comment]
> Hi and thanks for developing!
> 
> I have a custom GNU/Linux setup and I don't use Network Manager to connect to the Internet. Musicpod was working just fine for me a few versions ago. Now in version 1.8.1, it complains about having no network connection. In the terminal output, it says _The name org.freedesktop.NetworkManager was not provided by any .service files_ . So I have to start the Network Manager for it to work. Can there be an option to disable this check, or can it be avoided?

Hi! I recently added a fallback so if there is no networkmanager available musicpod should just assume there is network (but then just not show network images if you disconnect and streams etc)
Could you try from the edge channel and see if this fixes it for you?

**Comment by izobilje** [comment]
I built from git now and the issue is fixed. But there is a minor regression which I will describe separetely.
