### ISSUE TITLE
Must search by name before searching by tag, country, or language

### ISSUE THREAD

**Issue by izobilje** [ubuntu-flutter-community/musicpod#896]
In the version built from git, if after starting the program, I go straight to the radio search, and search by tag, country, or name, I get no results until I do any search (of podcasts or radio stations) by name. Then all the searches work. This is a regresion compared to version 1.8.1.

**Comment by Feichtmeier** [comment]
yeah those are just the strings :) will fix on the next release, I need to make sure I dont make them too often because windows and macos only have 1 "channel", the direct download

**Comment by Feichtmeier** [comment]
ah you know what, until tomorrow noone gonna open the music app anyways on macos :P (except @popey <3), fix incoming, release after, I need to make the snap release anyways still
