### ISSUE TITLE
Color theme problem

### ISSUE THREAD

**Issue by PetrBalvin** [ubuntu-flutter-community/musicpod#899]
After the update, it does not respect the color theme according to the system.

**Comment by Feichtmeier** [comment]
I'll fix later and push an dupdate for ubuntu

**Comment by Feichtmeier** [comment]
> After the update, it does not respect the color theme according to the system.

What linux desktop version do you use?
Just checked 24.04 and the color following on the system still works:

https://github.com/user-attachments/assets/0e776359-7062-483b-b8c6-1bfcf545ea02

**Comment by PetrBalvin** [comment]
https://github.com/user-attachments/assets/ccbd3a49-a8ed-48df-8d7b-868a4053940e

I use Ubuntu 24.04, Wayland, AMD. The problem occurs only when using Prussian Green theme, which I use as default. The orange theme only half works, some buttons stay weirdly green.

**Comment by Feichtmeier** [comment]
> Zaznam.obrazovky.z.2024-08-27.23-18-04.mp4
> 
> I use Ubuntu 24.04, Wayland, AMD. The problem occurs only when using Prussian Green theme, which I use as default. The orange theme only half works, some buttons stay weirdly green.

strange, alright I fixed a safe approach
Please test the edge later when it is ready (I guess in 30 mins)
Thanks for reporting! (we are currently testing yaru.dart changes because the colors will change with 24.10, since gnome finally supports a bunch of color variants :) )

**Comment by PetrBalvin** [comment]
With the orange theme, some buttons remain green, Prussian green is now fine.

**Comment by Feichtmeier** [comment]
> With the orange theme, some buttons remain green, Prussian green is now fine.

Yes that's the default yaru theme :) we have green buttons since years
