### ISSUE TITLE
Updating is not possible

### ISSUE THREAD

**Issue by dmaliog** [ubuntu-flutter-community/musicpod#915]
```
⋊> ~ on master ⨯ LANG=C yay                                                                                                 23:49:41
:: Synchronizing package databases...
 cachyos-v3 is up to date
 cachyos-core-v3 is up to date
 cachyos-extra-v3 is up to date
 cachyos is up to date
 endeavouros is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib                                           133,1 KiB   231 KiB/s 00:01 [---------------------------------------------] 100%
 chaotic-aur                                        727,2 KiB   122 KiB/s 00:06 [---------------------------------------------] 100%
:: Searching AUR for updates...
:: Searching databases for updates...
 -> gettext: local (0.22.5-1.1) is newer than core (0.22.5-1)
 -> reflector-simple: local (2024.8-1) is newer than cachyos (3.3-1)
 -> Packages not in AUR: scp-bin  spacecadetpinball
 -> Flagged Out Of Date AUR Packages: enchant1.6
:: 1 package to upgrade/install.
1  aur/musicpod  1.9.1-1 -> 1.10.1-2
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
 -> Excluding packages may cause partial upgrades and break systems
==> 
AUR Explicit (1): musicpod-1.10.1-2
:: PKGBUILD up to date, skipping download: musicpod
  1 musicpod                         (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
  1 musicpod                         (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: musicpod 1.10.1-2 (Вс 08 сен 2024 23:49:59)
==> Retrieving sources...
  -> Found musicpod-1.10.1.tar.gz
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    musicpod-1.10.1.tar.gz ... Passed
:: (1/1) Parsing SRCINFO: musicpod
==> Making package: musicpod 1.10.1-2 (Вс 08 сен 2024 23:49:59)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found musicpod-1.10.1.tar.gz
==> Validating source files with sha256sums...
    musicpod-1.10.1.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting musicpod-1.10.1.tar.gz with bsdtar
==> Sources are ready.
==> Making package: musicpod 1.10.1-2 (Вс 08 сен 2024 23:50:00)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Unhandled exception:
Invalid argument(s): The provided value "/home/dmali/.cache/yay/musicpod/fvm-cache/cache.git" is not the root of a git directory
#0      GitDir.fromExisting (package:git/src/git_dir.dart:475)
<asynchronous suspension>
#1      FlutterService.getReference (package:fvm/src/services/flutter_service.dart:205)
<asynchronous suspension>
#2      FlutterService.isTag (package:fvm/src/services/flutter_service.dart:169)
<asynchronous suspension>
#3      validateFlutterVersion (package:fvm/src/workflows/ensure_cache.workflow.dart:217)
<asynchronous suspension>
#4      ensureCacheWorkflow (package:fvm/src/workflows/ensure_cache.workflow.dart:27)
<asynchronous suspension>
#5      InstallCommand.run (package:fvm/src/commands/install_command.dart:75)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212)
<asynchronous suspension>
#7      FvmCommandRunner.runCommand (package:fvm/src/runner.dart:245)
<asynchronous suspension>
#8      FvmCommandRunner.run (package:fvm/src/runner.dart:124)
<asynchronous suspension>
#9      Scope.run (package:scope/src/scope.dart:151)
<asynchronous suspension>
#10     main (file:///tmp/pkg/src/fvm-3.2.1/bin/main.dart:13)
<asynchronous suspension>
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: musicpod-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
musicpod - exit status 4
⋊> ~ on master ⨯    
```

**Comment by Feichtmeier** [comment]
hi how did you install musicpod?

**Comment by dmaliog** [comment]
> hi how did you install musicpod?

Hello. Via AUR. I have an old version, but the new one does not want to update due to build errors.

**Comment by Feichtmeier** [comment]
@dongfengweixiao could you take a look please when you have time

**Comment by dmaliog** [comment]
> > > hi how did you install musicpod?
> > 
> > 
> > Hello. Via AUR. I have an old version, but the new one does not want to update due to build errors.
> 
> PLS try version 1.11.0-3.
Sorry for such a late response :)

`⋊> ~ on master ⨯ LANG=C yay -S musicpod                                                                                     18:18:53
AUR Explicit (1): musicpod-1.11.0-3
:: (1/1) Downloaded PKGBUILD: musicpod
  1 musicpod                         (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
  1 musicpod                         (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: musicpod 1.11.0-3 (Вс 15 сен 2024 18:19:26)
==> Retrieving sources...
  -> Downloading musicpod-1.11.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 23.3M    0 23.3M    0     0   151k      0 --:--:--  0:02:37 --:--:--  291k
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    musicpod-1.11.0.tar.gz ... Passed
:: (1/1) Parsing SRCINFO: musicpod
==> Making package: musicpod 1.11.0-3 (Вс 15 сен 2024 18:22:04)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found musicpod-1.11.0.tar.gz
==> Validating source files with sha256sums...
    musicpod-1.11.0.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting musicpod-1.11.0.tar.gz with bsdtar
==> Sources are ready.
==> Making package: musicpod 1.11.0-3 (Вс 15 сен 2024 18:22:05)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
Creating local mirror...
 Counting objects:    [██████████████████████████████████████████████████] 100%
 Compressing objects: [██████████████████████████████████████████████████] 100%
 Receiving objects:   [███...............................................] 5%Cloning into '/home/dmali/.cache/yay/musicpod/fvm-cache/cache.git'...

remote: Enumerating objects: 538027, done.        
remote: Counting objects:  75% (403/537)        
remote: Counting objects:  99% (532/537)        
remote: Counting objects: 100% (537/537), done.        
remote: Compressing objects:   5% (19/366)        
remote: Compressing objects:  35% (129/366)        
remote: Compressing objects:  56% (205/366)        
remote: Compressing objects:  62% (227/366)        
remote: Compressing objects:  99% (363/366)        
remote: Compressing objects: 100% (366/366), done.        

Receiving objects:   0% (1/538027)
Receiving objects:   0% (34/538027), 44.01 KiB | 34.00 KiB/s
Receiving objects:   0% (148/538027), 100.01 KiB | 58.00 KiB/s
Receiving objects:   0% (448/538027), 372.01 KiB | 138.00 KiB/s
Receiving objects:   0% (903/538027), 876.01 KiB | 236.00 KiB/s
Receiving objects:   0% (1562/538027), 1.58 MiB | 341.00 KiB/s 
Receiving objects:   0% (1970/538027), 2.31 MiB | 463.00 KiB/s
Receiving objects:   0% (2124/538027), 2.49 MiB | 465.00 KiB/s
Receiving objects:   0% (2218/538027), 2.54 MiB | 443.00 KiB/s
Receiving objects:   0% (2269/538027), 2.65 MiB | 355.00 KiB/s
Receiving objects:   0% (2281/538027), 2.68 MiB | 210.00 KiB/s
Receiving objects:   0% (2314/538027), 2.70 MiB | 122.00 KiB/s
Receiving objects:   0% (2432/538027), 2.83 MiB | 76.00 KiB/s 
Receiving objects:   0% (2721/538027), 3.17 MiB | 121.00 KiB/s
Receiving objects:   0% (3193/538027), 3.75 MiB | 218.00 KiB/s
Receiving objects:   0% (3885/538027), 4.51 MiB | 379.00 KiB/s
Receiving objects:   0% (4861/538027), 5.26 MiB | 549.00 KiB/s
Receiving objects:   0% (5017/538027), 5.38 MiB | 524.00 KiB/s
Receiving objects:   0% (5073/538027), 5.42 MiB | 379.00 KiB/s
Receiving objects:   0% (5265/538027), 5.56 MiB | 304.00 KiB/s
Receiving objects:   0% (5363/538027), 5.60 MiB | 247.00 KiB/s
Receiving objects:   1% (5381/538027), 5.60 MiB | 247.00 KiB/s
Receiving objects:   1% (5526/538027), 5.71 MiB | 117.00 KiB/s
Receiving objects:   1% (5634/538027), 5.82 MiB | 69.00 KiB/s 
Receiving objects:   1% (5655/538027), 5.84 MiB | 83.00 KiB/s
Receiving objects:   1% (5684/538027), 5.86 MiB | 56.00 KiB/s
Receiving objects:   1% (5728/538027), 5.86 MiB | 56.00 KiB/s
Receiving objects:   1% (5761/538027), 5.91 MiB | 46.00 KiB/s
Receiving objects:   1% (5778/538027), 5.93 MiB | 36.00 KiB/s
Receiving objects:   1% (5874/538027), 6.00 MiB | 29.00 KiB/s
Receiving objects:   1% (5917/538027), 6.02 MiB | 32.00 KiB/s
Receiving objects:   1% (5957/538027), 6.04 MiB | 30.00 KiB/s
Receiving objects:   1% (6216/538027), 6.17 MiB | 51.00 KiB/s
Receiving objects:   1% (6737/538027), 6.52 MiB | 106.00 KiB/s
Receiving objects:   1% (7559/538027), 7.09 MiB | 222.00 KiB/s
Receiving objects:   1% (8641/538027), 7.88 MiB | 378.00 KiB/s
Receiving objects:   1% (9881/538027), 8.76 MiB | 576.00 KiB/s
Receiving objects:   1% (10109/538027), 8.96 MiB | 558.00 KiB/s
Receiving objects:   1% (10191/538027), 8.98 MiB | 513.00 KiB/s
Receiving objects:   1% (10520/538027), 9.14 MiB | 426.00 KiB/s
Receiving objects:   2% (10761/538027), 9.30 MiB | 374.00 KiB/s
Receiving objects:   2% (11210/538027), 9.58 MiB | 346.00 KiB/s
Receiving objects:   2% (12316/538027), 10.22 MiB | 302.00 KiB/s
Receiving objects:   2% (13621/538027), 11.03 MiB | 435.00 KiB/s
Receiving objects:   2% (13937/538027), 11.18 MiB | 457.00 KiB/s
Receiving objects:   2% (14057/538027), 11.29 MiB | 426.00 KiB/s
Receiving objects:   2% (14109/538027), 11.33 MiB | 347.00 KiB/s
Receiving objects:   2% (14205/538027), 11.36 MiB | 290.00 KiB/s
Receiving objects:   2% (14330/538027), 11.43 MiB | 155.00 KiB/s
Receiving objects:   2% (14438/538027), 11.52 MiB | 66.00 KiB/s 
Receiving objects:   2% (14478/538027), 11.55 MiB | 49.00 KiB/s
Receiving objects:   2% (14505/538027), 11.57 MiB | 45.00 KiB/s
Receiving objects:   2% (14587/538027), 11.61 MiB | 46.00 KiB/s
Receiving objects:   2% (14750/538027), 11.66 MiB | 48.00 KiB/s
Receiving objects:   2% (15243/538027), 11.91 MiB | 79.00 KiB/s
Receiving objects:   2% (16081/538027), 12.39 MiB | 173.00 KiB/s
Receiving objects:   3% (16141/538027), 12.39 MiB | 173.00 KiB/s
Receiving objects:   3% (17291/538027), 13.10 MiB | 325.00 KiB/s
Receiving objects:   3% (18892/538027), 14.02 MiB | 522.00 KiB/s
Receiving objects:   3% (20602/538027), 14.97 MiB | 705.00 KiB/s
Receiving objects:   3% (20811/538027), 15.24 MiB | 676.00 KiB/s
Receiving objects:   3% (20880/538027), 15.27 MiB | 601.00 KiB/s
Receiving objects:   3% (20920/538027), 15.29 MiB | 496.00 KiB/s
Receiving objects:   3% (20933/538027), 15.31 MiB | 349.00 KiB/s
Receiving objects:   3% (20988/538027), 15.33 MiB | 279.00 KiB/s
Receiving objects:   3% (21269/538027), 15.50 MiB | 135.00 KiB/s
Receiving objects:   4% (21522/538027), 15.50 MiB | 135.00 KiB/s
Receiving objects:   4% (21904/538027), 15.68 MiB | 108.00 KiB/s
Receiving objects:   4% (22857/538027), 16.24 MiB | 154.00 KiB/s
Receiving objects:   4% (24192/538027), 16.98 MiB | 288.00 KiB/s
Receiving objects:   4% (25461/538027), 17.82 MiB | 535.00 KiB/s
Receiving objects:   4% (25848/538027), 18.21 MiB | 574.00 KiB/s
Receiving objects:   4% (25999/538027), 18.30 MiB | 489.00 KiB/s
Receiving objects:   4% (26160/538027), 18.35 MiB | 419.00 KiB/s
Receiving objects:   4% (26244/538027), 18.42 MiB | 279.00 KiB/s
Receiving objects:   4% (26255/538027), 18.43 MiB | 172.00 KiB/s
Receiving objects:   4% (26337/538027), 18.48 MiB | 53.00 KiB/s 
Receiving objects:   4% (26471/538027), 18.54 MiB | 48.00 KiB/s
Receiving objects:   5% (26902/538027), 18.82 MiB | 79.00 KiB/s
Receiving objects:   5% (26958/538027), 18.82 MiB | 79.00 KiB/s
Receiving objects:   5% (28058/538027), 19.54 MiB | 176.00 KiB/s
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2032 bytes of body are still expected

fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF

fatal: fetch-pack: invalid index-pack output


Exception: Git clone failed

Please run command with  --verbose if you want more information
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: musicpod-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
musicpod - exit status 4
⋊> ~ on master ⨯                                                                                                            `

**Comment by Feichtmeier** [comment]
@dmaliog is this fixed? I have no control over this
