### ISSUE TITLE
UI very unresponsive

### ISSUE THREAD

**Issue by DiogoConstantino** [ubuntu-flutter-community/musicpod#916]
I'm running Musicpod (0+git.f0a48e3 (1453) 54MB) on Ubuntu 24.04 with X11. And the UI is very slow and some parts of it like the search text box are even unusable (one character takes roughly 30 seconds to appear).

While launching it from the terminal I'm getting the following output:
`
iogo@diogo-B550-GAMING-X:~$ musicpod 
Gtk-Message: 12:04:24.515: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(musicpod:1429063): Gtk-WARNING **: 12:04:24.565: GTK+ module /snap/musicpod/1453/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 12:04:24.565: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:04:24.565: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(musicpod:1429063): Gtk-WARNING **: 12:04:24.566: GTK+ module /snap/musicpod/1453/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 12:04:24.566: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:04:24.566: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
package:media_kit_libs_linux registered.
media_kit: VideoOutput: video_output_new: 3017282817104
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 3017282817104, id: 3017077653392, rect: {left: 0, top: 0, width: 1, height: 1}}
flutter: NativeVideoController: Texture ID: 3017077653392

** (musicpod:1429063): WARNING **: 12:04:50.221: atk-bridge: get_device_events_reply: unknown signature

(musicpod:1429063): Gdk-CRITICAL **: 12:07:05.390: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed

`

While waiting for an event the window doesn't move and it's not resizeable.
Vertical scroll works normally.

Selecting a podcast will take a long time as it appears the rendering, is taking a very long time:
![image](https://github.com/user-attachments/assets/84efd7c7-e541-476c-b85e-5cca3bfd4be4)

This doens't happen on any other Flutter application I'm running.

**Comment by Feichtmeier** [comment]
> I'm running Musicpod (0+git.f0a48e3 (1453) 54MB) on Ubuntu 24.04 with X11. And the UI is very slow and some parts of it like the search text box are even unusable (one character takes roughly 30 seconds to appear).
> 
> While launching it from the terminal I'm getting the following output: ` iogo@diogo-B550-GAMING-X:~$ musicpod Gtk-Message: 12:04:24.515: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
> 
> (musicpod:1429063): Gtk-WARNING **: 12:04:24.565: GTK+ module /snap/musicpod/1453/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded. GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported. Gtk-Message: 12:04:24.565: Failed to load module "canberra-gtk-module" Gtk-Message: 12:04:24.565: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
> 
> (musicpod:1429063): Gtk-WARNING **: 12:04:24.566: GTK+ module /snap/musicpod/1453/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded. GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported. Gtk-Message: 12:04:24.566: Failed to load module "canberra-gtk-module" Gtk-Message: 12:04:24.566: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it. package:media_kit_libs_linux registered. media_kit: VideoOutput: video_output_new: 3017282817104 media_kit: VideoOutput: Using H/W rendering. flutter: VideoOutput.Resize flutter: {handle: 3017282817104, id: 3017077653392, rect: {left: 0, top: 0, width: 1, height: 1}} flutter: NativeVideoController: Texture ID: 3017077653392
> 
> ** (musicpod:1429063): WARNING **: 12:04:50.221: atk-bridge: get_device_events_reply: unknown signature
> 
> (musicpod:1429063): Gdk-CRITICAL **: 12:07:05.390: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
> 
> `
> 
> While waiting for an event the window doesn't move and it's not resizeable. Vertical scroll works normally.
> 
> Selecting a podcast will take a long time as it appears the rendering, is taking a very long time: ![image](https://private-user-images.githubusercontent.com/9408012/365628149-84efd7c7-e541-476c-b85e-5cca3bfd4be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzQxODUsIm5iZiI6MTcyNjIzMzg4NSwicGF0aCI6Ii85NDA4MDEyLzM2NTYyODE0OS04NGVmZDdjNy1lNTQxLTQ3NmMtYjg1ZS01Y2NhM2JmZDRiZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMTMyNDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE3MjZlNDMyZjAxNDMzMWIyYmE2YjEzNmY0MDNhNzZiODZhZmYwYjdiMzc0ZGNkODNiMDhjMDViZmU3OTVmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dRZLLBCNcIcDrT-uWWoocZONFPDNlG2EPb_luR6QdvI)
> 
> This doens't happen on any other Flutter application I'm running.

hm, I can not reproduce this even on a very weak and old (10 years intel) laptop :( did you restart the app/computer?

**Comment by DiogoConstantino** [comment]
> hm, I can not reproduce this even on a very weak and old (10 years intel) laptop :( did you restart the app/computer?

I have rebooted, this is a relatively powerful (midrange), but not very recent machine (rougly3 years).
Feel the described behaviour when changing from a view to another and when doing any search.

**Comment by Feichtmeier** [comment]
@DiogoConstantino is this still happening for you after updating to 2.4.0 ?

**Comment by leeadama** [comment]
This is happening for me as well.  I am using the Flatpak from Flathub.  

In my case it's only on the search tab.  Whenever the search tab gets focus the GUI freezes for what seems to be exactly 25 seconds.  

If I click on any other tab and go back to search it freezes.  If the search tab is selected and the app loses focus it freezes when I switch back to the app.  If the search tab was previously selected when I quit the app and I launch the app again it freezes.  It does it every time and it's always exactly 25 seconds.  Once the 25 seconds are up the app works normally and media continues playing while the GUI is frozen.

System Specs: AMD 5800X / RADEON 7800XT / 96GB DDR4 / Linux Mint 22.1 Cinnamon / 6.12.3-061203-generic / Mesa 25.0.1

Let me know if I can give you any more information or if I can help you track this down in any other way.

**Comment by Feichtmeier** [comment]
it must be something with a combination of certain hardware, the current flutter version and x11+linux (canonicals flutter apps are currently a bit outdated and still on 3.24, so maybe this is the difference :))
For flatpak it needs to wait until I make a new (stable) release. For snap the current main is in the edge channel
Sorry for the inconvenience but this def. is some flutter + hardware problem. I dont have any issues on 
- a very old crappy intel notebook
- a mid-old nvidia gaming pc with ubuntu and x11
- a very old nvidia card pc from my father
- macbooks
- windows machines

**Comment by Feichtmeier** [comment]
hey guys, can you check if this still happens with the snap from edge? or the flatpak 2.15.0
