### ISSUE TITLE
Let users select the downloads directory

### ISSUE THREAD

**Issue by LukeZBaker** [ubuntu-flutter-community/musicpod#928]
I built MusicPod using the AUR under Manjaro.

MusicPod has improved in leaps and bounds. Re downloading podcasts, where are they stored? I've searched my filesystem and didn't find them. 

Are there any plans to let the user choose where to save them?

**Comment by Feichtmeier** [comment]
> I built MusicPod using the AUR under Manjaro.
> 
> MusicPod has improved in leaps and bounds. Re downloading podcasts, where are they stored? I've searched my filesystem and didn't find them.
> 
> Are there any plans to let the user choose where to save them?

They are stored in the users download directory
Yeah I think I can add an option for this

**Comment by LukeZBaker** [comment]
Thanks for your response.

I've tested the Flatpak and the AUR package in Manjaro. After restarting the app, I can see podcasts are now being stored at ~/Downloads/musicpod

I'd suggest you add the appropriate file extension to the saved file (e.g. wav, mp3 or whatever format they are stored in).

Downloading is buggy on my system with errors when trying to download some podcasts such as 

DioException [unknown]: null
Error: RedirectException: Redirect limit exceeded.

I'll try testing with Ubuntu to see if I get the same errors.

**Comment by Feichtmeier** [comment]
@LukeZBaker custom downloads dir will land in 2.0, but I need @dongfengweixiao to update the AUR package for arch users then
