### ISSUE TITLE
The presence of a lost+found folder makes musicpod unable to load the users music library

### ISSUE THREAD

**Issue by anonymousguy31** [ubuntu-flutter-community/musicpod#934]
I moved my music library onto a newly formatted drive, and the music library would fail to load. The attached error log mentions musicpod is unable to read the lost+found folder due to insufficient permissions, which causes the entire library to fail in loading. I have reproduced this by moving the library to yet another newly partitioned drive, and the same problem occurred. 

This is fixable by deleting the lost+found directory, but given this is a hidden directory by default this issue has the potential to cause significant confusion for the user. I'd argue some kind of workaround would be called for, if possible. 

Thanks for your great work on this project, by the way. Best music app i've used in a while. 

![Screenshot from 2024-09-30 17-27-04](https://github.com/user-attachments/assets/2818e59c-4a6f-4d7d-a602-34e7c06df8a0)

**Comment by Feichtmeier** [comment]
@anonymousguy31 thanks for the issue!

I added a fix in the linked PR
in half an hour or so you should be able to download a new version from the snap edge channel (I see you use ubuntu)
Would appreciate if you could check if this resolves this issue, best regards

**Comment by anonymousguy31** [comment]
@Feichtmeier 

I seem to be getting a new error now: 

![Screenshot from 2024-10-01 13-57-32](https://github.com/user-attachments/assets/ac126b58-8ab5-4b92-adc3-b8ae95b0c5a1)

**Comment by anonymousguy31** [comment]
@Feichtmeier 

It shows this at start now, which I feel like is an acceptable fix. The message will only show once and it doesn't break any functionality. Thanks for the help. 

![Pasted image](https://github.com/user-attachments/assets/775fbc3a-6dff-4efd-ab38-940246af1b87)

**Comment by Feichtmeier** [comment]
> @Feichtmeier 
> 
> It shows this at start now, which I feel like is an acceptable fix. The message will only show once and it doesn't break any functionality. Thanks for the help. 
> 
> ![Pasted image](https://github.com/user-attachments/assets/775fbc3a-6dff-4efd-ab38-940246af1b87)
> 

Oh good 👍😊 yeah I pump the failed attempts into the output but apparently I messed up the theming of the snackbar at some point in the past. I'll fix this then and then I think the issue is fixed. Thanks for bringing this up this was a really important bug
