### ISSUE TITLE
Request: Play live button for radio playback

### ISSUE THREAD

**Issue by amugofjava** [ubuntu-flutter-community/musicpod#937]
When listening to the radio and pressing pause, it would be really useful to have a button that resumes live playback. 

Currently, pressing play will always resume where I left off. I can open the larger player window and drag the slider to the far right, but I do find sometimes this results in the slider and audio jumping around. A 'resume live' button would be really useful.

Video below shows result of dragging slider to the right - bar and audio jumps:

[Screencast from 2024-10-03 16-23-43.webm](https://github.com/user-attachments/assets/2907b0fd-44d7-47f5-b5d8-4365cac5c895)

Running Musicpod from the command line, I can't see any error messages written as the bar and audio jumps.

**Comment by Feichtmeier** [comment]
if we would put a refresh/restart screen button for stations right to the play/pause button, then I need something for the left side so it still looks centered :D any idea?

**Comment by amugofjava** [comment]
Ah! Yes, I know exactly what you mean :)

How about a stop button - to completely stop playback?
