### ISSUE TITLE
radio

### ISSUE THREAD

**Issue by senolfndk** [ubuntu-flutter-community/musicpod#939]
add manual radio add option

**Comment by Feichtmeier** [comment]
there is a manual radio add option...
https://github.com/user-attachments/assets/e455e3d6-6b87-4cc7-a289-7a00da73ae60

but I recommend to use the search instead

**Comment by senolfndk** [comment]
Sorry I didn't see it, thank you

**Comment by senolfndk** [comment]
Could you please add the album cover of the song that's playing?

**Comment by Feichtmeier** [comment]
> Could you please add the album cover of the song that's playing?

not sure what you are referring to:

- if you mean local music: if your local music is tagged correctly, including images all images should be shown
- if you mean radio streams, musicpod is actually one of the few apps that looks up the icytitle online and tries to fetch a corresponding album art, which does not always work
- if you mean podcasts, all artwork should be shown

**Comment by senolfndk** [comment]
I'm talking about radio broadcasts.

**Comment by Feichtmeier** [comment]
> I'm talking about radio broadcasts.

https://github.com/user-attachments/assets/f6fb9675-0f3f-405d-8bed-1d22316615f1

it is relying on musicbrainz and coverarchive, which do not always respond as desired and sometimes they are even not available

**Comment by senolfndk** [comment]
> > Radyo yayınlarından bahsediyorum.
> 
>  Bildschirmaufnahme.2024-09-19.um.20.43.44.mov 
> musicbrainz ve coverarchive'e güveniyor, bunlar her zaman istenildiği gibi yanıt vermiyor ve hatta bazen mevcut bile değil

hmm ok

**Comment by Feichtmeier** [comment]
> > > Radyo yayınlarından bahsediyorum.
> > 
> > 
> > Bildschirmaufnahme.2024-09-19.um.20.43.44.mov
> > musicbrainz ve coverarchive'e güveniyor, bunlar her zaman istenildiği gibi yanıt vermiyor ve hatta bazen mevcut bile değil
> 
> hmm ok

ah.. just checked .... the internet archive is currently down because of that attack, that's why the cover art lookup is currently never working. I guess tomorrow it will work again 🤞🏻
