### ISSUE TITLE
DiscordRPC does not work inside the snap

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/musicpod#946]
Fails with

```
thread 'frb_workerpool' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/discord-rich-presence-0.2.4/src/ipc_unix.rs:90:43:
Client not connected
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'PanicException'
#0      FlutterRustBridgeBase._transformRust2DartMessage (package:flutter_rust_bridge/src/basic.dart:128)
#1      FlutterRustBridgeBase.executeNormal.<anonymous closure> (package:flutter_rust_bridge/src/basic.dart:70)
<asynchronous suspension>
#2      FlutterDiscordRPC.setActivity (package:flutter_discord_rpc/src/flutter_discord_rpc_base.dart:81)
<asynchronous suspension>
```

I am using this dart package which is using this rust package:

https://github.com/KRTirtho/frb_plugins/blob/main/packages/flutter_discord_rpc/native/Cargo.toml#L18C1-L18C22

in the rust package that is being there used this is the line where it wants to create a unix socket:

https://github.com/vionya/discord-rich-presence/blob/18ecbe78c7030a31932efb550e738fef94aa7a6b/src/ipc_unix.rs#L90

@kenvandine do you know if this doable with the snap with any plug/slot?
I disable this for now for linux and added a toggle setting for all inside settings

**Comment by soumyaDghosh** [comment]
I know, how to fix it but it needs changes in the upstream source code. Basically, the code is searching in a path is non-existent to snap context.

In snap, the `XDG_RUNTIME_DIR` is `/run/user/1000/snap.musicpod/`

Now, discord-ipc is in `/run/user/1000/snap.discord/`. The `snap.discord` folder is accounted, but you cannot access this path normally from musicpod. So, for that the path of the ipc has to be like this

`$XDG_RUNTIME_DIR/../snap.discord/ipc` or wherever the discord ipc is.


The problem is, I am a very big noob in rust... So, not sure if I'll be able to fix it.

**Comment by Feichtmeier** [comment]
> I know, how to fix it but it needs changes in the upstream source code. Basically, the code is searching in a path is non-existent to snap context.
> 
> In snap, the `XDG_RUNTIME_DIR` is `/run/user/1000/snap.musicpod/`
> 
> Now, discord-ipc is in `/run/user/1000/snap.discord/`. The `snap.discord` folder is accounted, but you cannot access this path normally from musicpod. So, for that the path of the ipc has to be like this
> 
> `$XDG_RUNTIME_DIR/../snap.discord/ipc` or wherever the discord ipc is.
> 
> The problem is, I am a very big noob in rust... So, not sure if I'll be able to fix it.

Wow thanks for this analysis!

@KRTirtho is this something you would be willing to change in your library? (and best regards)

**Comment by soumyaDghosh** [comment]
Needed to fix

- [ ] https://github.com/vionya/discord-rich-presence/pull/42 
       or some other way to fix the path if my logic in rust is incorrect
- [ ] A way to get read and write access to the discord ipc unix socket from within the snap sandbox
    possible ways:
        - A universal plug to discord ipc socket
        - A rw access via system-files plug

**Comment by Feichtmeier** [comment]
Thanks @soumyaDghosh !
The patch won't probably be merged unless you remove those print statements again :P 

I need to resync our fork again with your branch of the rust dep
Then we could test the snap again

>  - A rw access via system-files plug

what would we need to change inside snapcraft.yaml for this?
