### ISSUE TITLE
musicpod does not recognize connection

### ISSUE THREAD

**Issue by FGYada1984** [ubuntu-flutter-community/musicpod#949]
Everything was working fine, but today when I went to open musicpod it doesn't recognize that I have internet and works for any other application. I use vpn, but i've tried with it disabled.  I've already uninstalled and reinstalled it, cleared the user data. launching the program via terminal I'm getting the following log (from what I understand, it doesn't have any specific connection problems.):

![image](https://github.com/user-attachments/assets/e8f7e930-04f1-4d41-b3dd-499247a463b3)

another problem is that when i click close, it crashes. but the biggest problem is that i can't connect.

![image](https://github.com/user-attachments/assets/08fe5ef7-9590-4d54-abca-4262ad48ccf8)
![image](https://github.com/user-attachments/assets/0941c662-cae2-4943-8780-2a68276e8e3d)

OS: Arch Linux x86_64
DE: GNOME 47.0
WM: Mutter (Wayland)

**Comment by Feichtmeier** [comment]
Hi 👋🏻 
thanks for using musicpod

the arch port is made by @dongfengweixiao 
I assume this is the old problem that network manager is not used on all systems
do you use network manager or netplan?
best regards

**Comment by Feichtmeier** [comment]
I added a fallback = Wifi now if the connectivity chck fails for whatever reason, it does not feel good but at least you can use the app :P. 
this will land in stable 2.0 release and then hopefully @dongfengweixiao is so nice an updates the arch release

**Comment by FGYada1984** [comment]
> Hi 👋🏻 thanks for using musicpod
> 
> the arch port is made by @dongfengweixiao I assume this is the old problem that network manager is not used on all systems do you use network manager or netplan? best regards

thanks for the quick reply! and just to contribute, yes, i use network mananger.
